Repository Lovely-4K/love-backend, pull requests merged in 2023-12, with the labels that each got.

#198 refactor: 다이어리 지도 조회시 쿼리 수정
  model/src/main/java/com/lovely4k/backend/diary/DiaryRepository.java
Labels: refactor

#195 fix : 랜덤 색상 hexcode 수정
  model/src/main/java/com/lovely4k/backend/member/Member.java
  model/src/main/java/com/lovely4k/backend/member/util/MemberRandomUtils.java
Labels: fix

#177 refactor : 이미지 처리 최적화(리사이징, 병렬 처리)
  api/build.gradle
  api/src/main/java/com/lovely4k/backend/common/imageuploader/AWSS3Uploader.java
  api/src/main/java/com/lovely4k/backend/common/imageuploader/ImageResizer.java
  api/src/main/java/com/lovely4k/backend/common/imageuploader/ResizedMultipartFile.java
  api/src/main/java/com/lovely4k/backend/diary/service/DiaryService.java
  api/src/main/resources/application-local.yaml
  api/src/test/java/com/lovely4k/backend/IntegrationTestSupport.java
  api/src/test/java/com/lovely4k/backend/couple/IncreaseTemperatureEventHandlerTest.java
  api/src/test/java/com/lovely4k/backend/couple/service/CoupleServiceConcurrencyTest.java
Labels: refactor

#202 fix : 커플 프로필 조회 시 coupleStatus 변수 추가
  api/src/docs/asciidoc/api/couple/couple-profile-get.adoc
  api/src/main/java/com/lovely4k/backend/couple/service/response/CoupleProfileGetResponse.java
  api/src/test/java/com/lovely4k/backend/couple/controller/CoupleControllerTest.java
  api/src/test/java/com/lovely4k/docs/couple/CoupleControllerDocsTest.java
  model/src/main/java/com/lovely4k/backend/couple/Couple.java
  model/src/main/java/com/lovely4k/backend/couple/CoupleStatus.java
  model/src/main/java/com/lovely4k/backend/couple/repository/CoupleQueryRepository.java
  model/src/main/java/com/lovely4k/backend/couple/repository/response/FindCoupleProfileResponse.java
Labels: fix

#204 Release-3.1
  api/src/docs/asciidoc/api/couple/couple-profile-get.adoc
  api/src/main/java/com/lovely4k/backend/common/db/DataSourceConfig.java
  api/src/main/java/com/lovely4k/backend/common/db/DatabaseType.java
  api/src/main/java/com/lovely4k/backend/common/db/LoadBalancer.java
  api/src/main/java/com/lovely4k/backend/common/db/RoutingDataSource.java
  api/src/main/java/com/lovely4k/backend/couple/service/response/CoupleProfileGetResponse.java
  api/src/test/java/com/lovely4k/backend/common/db/LoadBalancerTest.java
  api/src/test/java/com/lovely4k/backend/couple/controller/CoupleControllerTest.java
  api/src/test/java/com/lovely4k/docs/couple/CoupleControllerDocsTest.java
  model/src/main/java/com/lovely4k/backend/couple/Couple.java
  model/src/main/java/com/lovely4k/backend/couple/CoupleStatus.java
  model/src/main/java/com/lovely4k/backend/couple/repository/CoupleQueryRepository.java
  model/src/main/java/com/lovely4k/backend/couple/repository/response/FindCoupleProfileResponse.java
Labels: release

#203 fix : 권한 설정 오류 해결
  api/src/docs/asciidoc/api/couple/couple-profile-get.adoc
  api/src/main/java/com/lovely4k/backend/authentication/exception/AccessDeniedHandlerException.java
  api/src/main/java/com/lovely4k/backend/authentication/token/JwtFilter.java
  api/src/main/java/com/lovely4k/backend/authentication/token/SecurityConfig.java
  api/src/main/java/com/lovely4k/backend/authentication/token/UserDetailsImpl.java
  api/src/main/java/com/lovely4k/backend/common/db/DataSourceConfig.java
  api/src/main/java/com/lovely4k/backend/common/db/DatabaseType.java
  api/src/main/java/com/lovely4k/backend/common/db/LoadBalancer.java
  api/src/main/java/com/lovely4k/backend/common/db/RoutingDataSource.java
  api/src/main/java/com/lovely4k/backend/couple/service/response/CoupleProfileGetResponse.java
  api/src/main/java/com/lovely4k/backend/health/HealthChecker.java
  api/src/main/resources/application-local.yaml
  api/src/test/java/com/lovely4k/backend/common/db/LoadBalancerTest.java
  api/src/test/java/com/lovely4k/backend/couple/controller/CoupleControllerTest.java
  api/src/test/java/com/lovely4k/docs/couple/CoupleControllerDocsTest.java
  api/src/test/resources/application.yaml
  model/src/main/java/com/lovely4k/backend/couple/Couple.java
  model/src/main/java/com/lovely4k/backend/couple/CoupleStatus.java
  model/src/main/java/com/lovely4k/backend/couple/repository/CoupleQueryRepository.java
  model/src/main/java/com/lovely4k/backend/couple/repository/response/FindCoupleProfileResponse.java
Labels: fix

#178 chore : 캐시 설정 추가
  api/build.gradle
  api/src/main/java/com/lovely4k/backend/calendar/service/CalendarCommandService.java
  api/src/main/java/com/lovely4k/backend/calendar/service/CalendarQueryService.java
  api/src/main/java/com/lovely4k/backend/common/cache/CacheEvictedEvent.java
  api/src/main/java/com/lovely4k/backend/common/cache/CustomCacheManager.java
  api/src/main/java/com/lovely4k/backend/common/config/CacheConfig.java
  api/src/main/java/com/lovely4k/backend/couple/service/CoupleService.java
  api/src/main/java/com/lovely4k/backend/diary/service/DiaryQueryService.java
  api/src/main/java/com/lovely4k/backend/diary/service/DiaryService.java
  api/src/main/java/com/lovely4k/backend/member/service/MemberService.java
  api/src/main/java/com/lovely4k/backend/question/service/QuestionQueryService.java
  api/src/main/java/com/lovely4k/backend/question/service/QuestionService.java
  api/src/main/resources/application-local.yaml
Labels: chore
