Repository Lovely-4K/love-backend, pull requests merged in 2023-11, with the labels that each got.

#72 chore : yaml, docs 설정 변경
  .gitignore
  api/src/main/java/com/lovely4k/backend/common/config/WebConfig.java
  api/src/main/resources/application-local.yaml
  api/src/main/resources/application.yaml
  api/src/main/resources/static/hello.html
  api/src/test/java/com/lovely4k/backend/ControllerTestSupport.java
  api/src/test/resources/application.yaml
  build.gradle
  model/src/test/resources/application.yaml
Labels: bug, chore

#73 chore : yaml, docs 설정 변경
  .gitignore
  api/src/main/java/com/lovely4k/backend/common/config/WebConfig.java
  api/src/main/resources/application-local.yaml
  api/src/main/resources/application.yaml
  api/src/main/resources/static/hello.html
  api/src/test/java/com/lovely4k/backend/ControllerTestSupport.java
  api/src/test/resources/application.yaml
  build.gradle
  model/src/test/resources/application.yaml
Labels: bug, chore

#74 chore : main 브랜치 분기 조정
  .github/workflows/main.yml
Labels: chore

#86 refactor : 프론트 의견 반영
  api/src/main/java/com/lovely4k/backend/couple/service/response/CoupleProfileGetResponse.java
  api/src/main/java/com/lovely4k/backend/member/service/response/MemberProfileGetResponse.java
  api/src/test/java/com/lovely4k/backend/couple/controller/CoupleControllerTest.java
  api/src/test/java/com/lovely4k/backend/member/controller/MemberControllerTest.java
  api/src/test/java/com/lovely4k/backend/member/service/MemberServiceTest.java
  api/src/test/java/com/lovely4k/docs/couple/CoupleControllerDocsTest.java
  api/src/test/java/com/lovely4k/docs/member/MemberControllerDocsTest.java
Labels: refactor

#87 Release 1.1 -> Dev
  .github/workflows/main.yml
  api/build.gradle
  api/src/main/java/com/lovely4k/backend/couple/service/response/CoupleProfileGetResponse.java
  api/src/main/java/com/lovely4k/backend/member/service/response/MemberProfileGetResponse.java
  api/src/main/resources/static/hello.html
  api/src/test/java/com/lovely4k/backend/couple/controller/CoupleControllerTest.java
  api/src/test/java/com/lovely4k/backend/member/controller/MemberControllerTest.java
  api/src/test/java/com/lovely4k/backend/member/service/MemberServiceTest.java
  api/src/test/java/com/lovely4k/docs/couple/CoupleControllerDocsTest.java
  api/src/test/java/com/lovely4k/docs/member/MemberControllerDocsTest.java
Labels: bug, refactor

#92 fix : Release 1.2
  api/src/docs/asciidoc/api/question/questions.adoc
  api/src/main/java/com/lovely4k/backend/couple/service/CoupleService.java
  api/src/main/java/com/lovely4k/backend/couple/service/response/CoupleProfileGetResponse.java
  api/src/main/java/com/lovely4k/backend/diary/service/response/DiaryDetailResponse.java
  api/src/main/java/com/lovely4k/backend/member/service/response/MemberProfileGetResponse.java
  api/src/main/java/com/lovely4k/backend/question/controller/QuestionController.java
  api/src/main/java/com/lovely4k/backend/question/service/QuestionQueryService.java
  api/src/main/java/com/lovely4k/backend/question/service/QuestionService.java
  api/src/main/java/com/lovely4k/backend/question/service/request/CreateQuestionFormServiceRequest.java
  api/src/main/java/com/lovely4k/backend/question/service/response/CreateQuestionFormResponse.java
  api/src/main/java/com/lovely4k/backend/question/service/response/CreateQuestionResponse.java
  api/src/main/java/com/lovely4k/backend/question/service/response/DailyQuestionResponse.java
  api/src/main/java/com/lovely4k/backend/question/service/response/QuestionDetailsResponse.java
  api/src/main/resources/schema/schema.sql
  api/src/test/java/com/lovely4k/TestData.java
  api/src/test/java/com/lovely4k/backend/ControllerTestSupport.java
  api/src/test/java/com/lovely4k/backend/architect/ArchTests.java
  api/src/test/java/com/lovely4k/backend/couple/controller/CoupleControllerTest.java
  api/src/test/java/com/lovely4k/backend/question/service/QuestionQueryServiceTest.java
  api/src/test/java/com/lovely4k/docs/couple/CoupleControllerDocsTest.java
  api/src/test/java/com/lovely4k/docs/diary/DiaryControllerDocsTest.java
  api/src/test/java/com/lovely4k/docs/member/MemberControllerDocsTest.java
  api/src/test/java/com/lovely4k/docs/question/QuestionApiDocsTest.java
  model/build.gradle
  model/src/main/java/com/lovely4k/backend/common/jpa/JpaConfig.java
  model/src/main/java/com/lovely4k/backend/question/QuestionForm.java
  model/src/main/java/com/lovely4k/backend/question/QuestionFormType.java
  model/src/main/java/com/lovely4k/backend/question/repository/QuestionFormRepository.java
  model/src/main/java/com/lovely4k/backend/question/repository/QuestionQueryRepository.java
  model/src/main/java/com/lovely4k/backend/question/repository/response/QuestionDetailsResponse.java
  model/src/test/java/com/lovely4k/backend/question/QuestionTest.java
  model/src/test/java/com/lovely4k/backend/question/repository/QuestionFormRepositoryTest.java
  model/src/test/java/com/lovely4k/backend/question/repository/QuestionQueryRepositoryTest.java
  model/src/test/java/com/lovely4k/backend/question/repository/QuestionRepositoryTest.java
  model/src/test/resources/application.yaml
  model/src/test/resources/question.sql
  model/src/test/resources/questionForm.sql
  model/src/test/resources/test.sql
Labels: fix

#93 fix : Release 1.2
  api/src/docs/asciidoc/api/member/member-profile-edit.adoc
  api/src/docs/asciidoc/api/question/questions.adoc
  api/src/main/java/com/lovely4k/backend/common/imageuploader/AWSS3Uploader.java
  api/src/main/java/com/lovely4k/backend/common/imageuploader/ImageUploader.java
  api/src/main/java/com/lovely4k/backend/couple/service/CoupleService.java
  api/src/main/java/com/lovely4k/backend/couple/service/response/CoupleProfileGetResponse.java
  api/src/main/java/com/lovely4k/backend/diary/service/response/DiaryDetailResponse.java
  api/src/main/java/com/lovely4k/backend/member/controller/MemberController.java
  api/src/main/java/com/lovely4k/backend/member/controller/request/MemberProfileEditRequest.java
  api/src/main/java/com/lovely4k/backend/member/service/MemberService.java
  api/src/main/java/com/lovely4k/backend/member/service/request/MemberProfileEditServiceRequest.java
  api/src/main/java/com/lovely4k/backend/member/service/response/MemberProfileGetResponse.java
  api/src/main/java/com/lovely4k/backend/question/controller/QuestionController.java
  api/src/main/java/com/lovely4k/backend/question/service/QuestionQueryService.java
  api/src/main/java/com/lovely4k/backend/question/service/QuestionService.java
  api/src/main/java/com/lovely4k/backend/question/service/request/CreateQuestionFormServiceRequest.java
  api/src/main/java/com/lovely4k/backend/question/service/response/CreateQuestionFormResponse.java
  api/src/main/java/com/lovely4k/backend/question/service/response/CreateQuestionResponse.java
  api/src/main/java/com/lovely4k/backend/question/service/response/DailyQuestionResponse.java
  api/src/main/java/com/lovely4k/backend/question/service/response/QuestionDetailsResponse.java
  api/src/main/resources/schema/schema.sql
  api/src/test/java/com/lovely4k/TestData.java
  api/src/test/java/com/lovely4k/backend/ControllerTestSupport.java
  api/src/test/java/com/lovely4k/backend/architect/ArchTests.java
  api/src/test/java/com/lovely4k/backend/common/imageuploader/AWSS3UploaderTest.java
  api/src/test/java/com/lovely4k/backend/couple/controller/CoupleControllerTest.java
  api/src/test/java/com/lovely4k/backend/member/controller/MemberControllerTest.java
  api/src/test/java/com/lovely4k/backend/member/service/MemberServiceTest.java
  api/src/test/java/com/lovely4k/backend/question/service/QuestionQueryServiceTest.java
  api/src/test/java/com/lovely4k/backend/question/service/QuestionServiceConcurrencyTest.java
  api/src/test/java/com/lovely4k/backend/question/service/QuestionServiceTest.java
  api/src/test/java/com/lovely4k/docs/couple/CoupleControllerDocsTest.java
  api/src/test/java/com/lovely4k/docs/diary/DiaryControllerDocsTest.java
  api/src/test/java/com/lovely4k/docs/member/MemberControllerDocsTest.java
  api/src/test/java/com/lovely4k/docs/question/QuestionApiDocsTest.java
  model/build.gradle
  model/src/main/java/com/lovely4k/backend/common/jpa/JpaConfig.java
  model/src/main/java/com/lovely4k/backend/member/Member.java
  model/src/main/java/com/lovely4k/backend/question/QuestionForm.java
  model/src/main/java/com/lovely4k/backend/question/QuestionFormType.java
  model/src/main/java/com/lovely4k/backend/question/repository/QuestionFormRepository.java
  model/src/main/java/com/lovely4k/backend/question/repository/QuestionQueryRepository.java
  model/src/main/java/com/lovely4k/backend/question/repository/response/QuestionDetailsResponse.java
  model/src/test/java/com/lovely4k/backend/question/QuestionTest.java
  model/src/test/java/com/lovely4k/backend/question/repository/QuestionFormRepositoryTest.java
  model/src/test/java/com/lovely4k/backend/question/repository/QuestionQueryRepositoryTest.java
  model/src/test/java/com/lovely4k/backend/question/repository/QuestionRepositoryTest.java
  model/src/test/resources/application.yaml
  model/src/test/resources/question.sql
  model/src/test/resources/questionForm.sql
  model/src/test/resources/test.sql
Labels: fix

#94 feat : prod 파일 분리 및 actuator 도입
  api/build.gradle
  api/src/main/resources/application-prod1.yaml
  api/src/main/resources/application-prod2.yaml
  api/src/main/resources/application.yaml
Labels: feat

#88 feat : Controller Logging AOP 작업
  api/src/main/java/com/lovely4k/backend/common/log/HttpAspect.java
  api/src/main/java/com/lovely4k/backend/common/log/HttpLog.java
  api/src/main/java/com/lovely4k/backend/common/log/Pointcuts.java
  api/src/main/java/com/lovely4k/backend/common/log/RequestWrapper.java
  api/src/main/resources/application.yaml
  api/src/test/java/com/lovely4k/backend/common/log/RequestWrapperTest.java
  api/src/test/resources/application.yaml
Labels: feat

#80 feat : couple-delete
  api/src/main/java/com/lovely4k/backend/common/ExceptionMessage.java
  api/src/main/java/com/lovely4k/backend/common/GlobalExceptionHandler.java
  api/src/main/java/com/lovely4k/backend/couple/controller/CoupleController.java
  api/src/main/java/com/lovely4k/backend/couple/service/CoupleService.java
  api/src/main/resources/schema/schema.sql
  api/src/test/java/com/lovely4k/backend/couple/service/CoupleServiceTest.java
  api/src/test/java/com/lovely4k/docs/couple/CoupleControllerDocsTest.java
  model/src/main/java/com/lovely4k/backend/couple/Couple.java
  model/src/test/java/com/lovely4k/backend/couple/CoupleTest.java
Labels: feat

#77 feat : temperature
  api/src/main/java/com/lovely4k/backend/couple/service/CoupleService.java
  api/src/main/java/com/lovely4k/backend/couple/service/IncreaseTemperatureFacade.java
  api/src/main/java/com/lovely4k/backend/diary/service/DiaryService.java
  api/src/main/java/com/lovely4k/backend/question/service/QuestionService.java
  api/src/test/java/com/lovely4k/backend/architect/ArchTests.java
  api/src/test/java/com/lovely4k/backend/couple/service/CoupleServiceTest.java
  api/src/test/java/com/lovely4k/backend/couple/service/IncreaseTemperatureFacadeTest.java
  api/src/test/java/com/lovely4k/backend/diary/service/DiaryServiceTest.java
  api/src/test/java/com/lovely4k/backend/question/service/QuestionServiceTest.java
  model/src/main/java/com/lovely4k/backend/couple/Couple.java
  model/src/main/java/com/lovely4k/backend/couple/repository/CoupleRepository.java
  model/src/test/java/com/lovely4k/backend/couple/CoupleTest.java
Labels: feat

#95 refactor : AWS Image upload시 반환 url 변경
  api/src/main/java/com/lovely4k/backend/common/imageuploader/AWSS3Uploader.java
Labels: refactor

#85 docs : calendar api 문서 작성
  api/src/main/java/com/lovely4k/backend/calendar/controller/CalendarController.java
  api/src/main/java/com/lovely4k/backend/calendar/controller/request/CreateCalendarRequest.java
  api/src/main/java/com/lovely4k/backend/calendar/controller/request/FindAllCalendarsWithDateRequest.java
  api/src/main/java/com/lovely4k/backend/calendar/controller/request/UpdateCalendarRequest.java
  api/src/main/java/com/lovely4k/backend/calendar/service/CalendarCommandService.java
  api/src/main/java/com/lovely4k/backend/calendar/service/CalendarQueryService.java
  api/src/main/java/com/lovely4k/backend/calendar/service/request/CreateCalendarServiceReqeust.java
  api/src/main/java/com/lovely4k/backend/calendar/service/request/UpdateCalendarServiceRequest.java
  api/src/main/java/com/lovely4k/backend/calendar/service/response/CreateCalendarResponse.java
  api/src/main/java/com/lovely4k/backend/calendar/service/response/FindAllCalendarsWithDateServiceRequest.java
  api/src/main/java/com/lovely4k/backend/calendar/service/response/FindAllCalendarsWithDateServiceResponse.java
  api/src/main/java/com/lovely4k/backend/calendar/service/response/FindRecentCalendarsServiceResponse.java
  api/src/main/java/com/lovely4k/backend/calendar/service/response/ScheduleServiceResponse.java
  api/src/main/java/com/lovely4k/backend/calendar/service/response/UpdateCalendarResponse.java
  api/src/main/java/com/lovely4k/backend/common/log/HttpAspect.java
  api/src/main/java/com/lovely4k/backend/common/log/HttpLogResponse.java
  api/src/main/java/com/lovely4k/backend/question/controller/QuestionController.java
  api/src/main/resources/schema/schema.sql
  api/src/test/java/com/lovely4k/backend/architect/ArchTests.java
  api/src/test/java/com/lovely4k/docs/calendar/CalendarApiDocsTest.java
  api/src/test/resources/application.yaml
  model/src/main/java/com/lovely4k/backend/calendar/Calendar.java
  model/src/main/java/com/lovely4k/backend/calendar/ScheduleType.java
  model/src/main/java/com/lovely4k/backend/calendar/repository/CalendarCommandRepository.java
  model/src/main/java/com/lovely4k/backend/calendar/repository/CalendarQueryRepository.java
  model/src/main/java/com/lovely4k/backend/calendar/repository/response/ColorResponse.java
  model/src/main/java/com/lovely4k/backend/calendar/repository/response/FindAllCalendarsWithDateResponse.java
  model/src/main/java/com/lovely4k/backend/calendar/repository/response/FindRecentCalendarsResponse.java
  model/src/main/java/com/lovely4k/backend/calendar/repository/response/ScheduleResponse.java
Labels: docs

#99 feat : 소셜 로그인 구현 및 변경 [#98]
  .gitignore
  api/build.gradle
  api/src/main/java/com/lovely4k/backend/authentication/MyOAuth2Member.java
  api/src/main/java/com/lovely4k/backend/authentication/OAuth2UserService.java
  api/src/main/java/com/lovely4k/backend/authentication/OAuthAttributes.java
  api/src/main/java/com/lovely4k/backend/authentication/SecurityConfig.java
  api/src/main/java/com/lovely4k/backend/common/config/RetryConfig.java
  api/src/main/java/com/lovely4k/backend/common/config/WebConfig.java
  api/src/main/java/com/lovely4k/backend/common/sessionuser/LoginUser.java
  api/src/main/java/com/lovely4k/backend/common/sessionuser/LoginUserArgumentResolver.java
  api/src/main/java/com/lovely4k/backend/common/sessionuser/MemberInfo.java
  api/src/main/java/com/lovely4k/backend/common/sessionuser/SessionUser.java
  api/src/main/java/com/lovely4k/backend/couple/controller/CoupleController.java
  api/src/main/java/com/lovely4k/backend/couple/service/CoupleService.java
  api/src/main/java/com/lovely4k/backend/diary/controller/DiaryController.java
  api/src/main/java/com/lovely4k/backend/health/HealthChecker.java
  api/src/main/java/com/lovely4k/backend/member/controller/MemberController.java
  api/src/main/java/com/lovely4k/backend/member/controller/request/MemberProfileEditRequest.java
  api/src/main/java/com/lovely4k/backend/member/service/MemberService.java
  api/src/main/java/com/lovely4k/backend/member/service/request/MemberProfileEditServiceRequest.java
  api/src/main/java/com/lovely4k/backend/member/service/response/MemberProfileGetResponse.java
  api/src/main/java/com/lovely4k/backend/question/controller/QuestionController.java
  api/src/main/java/com/lovely4k/backend/question/service/QuestionQueryService.java
  api/src/main/java/com/lovely4k/backend/question/service/QuestionService.java
  api/src/main/resources/application.yaml
  api/src/main/resources/schema/schema.sql
  api/src/test/java/com/lovely4k/backend/ControllerTestSupport.java
  api/src/test/java/com/lovely4k/backend/architect/ArchTests.java
  api/src/test/java/com/lovely4k/backend/common/log/HttpAspectTest.java
  api/src/test/java/com/lovely4k/backend/couple/controller/CoupleControllerTest.java
  api/src/test/java/com/lovely4k/backend/couple/service/CoupleServiceTest.java
  api/src/test/java/com/lovely4k/backend/diary/controller/DiaryControllerTest.java
  api/src/test/java/com/lovely4k/backend/diary/service/DiaryServiceTest.java
  api/src/test/java/com/lovely4k/backend/diary/service/request/DiaryCreateRequestTest.java
  api/src/test/java/com/lovely4k/backend/member/controller/MemberControllerTest.java
  api/src/test/java/com/lovely4k/backend/member/service/MemberServiceTest.java
  api/src/test/java/com/lovely4k/backend/question/controller/QuestionControllerTest.java
  api/src/test/java/com/lovely4k/backend/question/service/QuestionQueryServiceTest.java
  api/src/test/java/com/lovely4k/backend/question/service/QuestionServiceConcurrencyTest.java
  api/src/test/java/com/lovely4k/backend/question/service/QuestionServiceTest.java
  api/src/test/java/com/lovely4k/docs/RestDocsSupport.java
  api/src/test/java/com/lovely4k/docs/couple/CoupleControllerDocsTest.java
  api/src/test/java/com/lovely4k/docs/diary/DiaryControllerDocsTest.java
  api/src/test/java/com/lovely4k/docs/member/MemberControllerDocsTest.java
  api/src/test/java/com/lovely4k/docs/question/QuestionApiDocsTest.java
  api/src/test/resources/application.yaml
  build.gradle
  model/src/main/java/com/lovely4k/backend/member/Member.java
  model/src/main/java/com/lovely4k/backend/member/Role.java
  model/src/main/java/com/lovely4k/backend/member/Sex.java
  model/src/main/java/com/lovely4k/backend/member/repository/MemberRepository.java
  model/src/test/java/com/lovely4k/backend/diary/DiaryTest.java
  model/src/test/java/com/lovely4k/backend/member/MemberTest.java
Labels: feat

#116 Release 2.1
  .gitignore
  api/build.gradle
  api/src/docs/asciidoc/api/diary/diary-create.adoc
  api/src/docs/asciidoc/api/login/login.adoc
  api/src/docs/asciidoc/api/question/questions.adoc
  api/src/docs/asciidoc/index.adoc
  api/src/main/java/com/lovely4k/backend/authentication/MyOAuth2Member.java
  api/src/main/java/com/lovely4k/backend/authentication/OAuth2UserService.java
  api/src/main/java/com/lovely4k/backend/authentication/OAuthAttributes.java
  api/src/main/java/com/lovely4k/backend/authentication/SecurityConfig.java
  api/src/main/java/com/lovely4k/backend/common/config/RetryConfig.java
  api/src/main/java/com/lovely4k/backend/common/config/WebConfig.java
  api/src/main/java/com/lovely4k/backend/common/sessionuser/LoginUser.java
  api/src/main/java/com/lovely4k/backend/common/sessionuser/LoginUserArgumentResolver.java
  api/src/main/java/com/lovely4k/backend/common/sessionuser/MemberInfo.java
  api/src/main/java/com/lovely4k/backend/common/sessionuser/SessionUser.java
  api/src/main/java/com/lovely4k/backend/couple/controller/CoupleController.java
  api/src/main/java/com/lovely4k/backend/couple/service/CoupleService.java
  api/src/main/java/com/lovely4k/backend/diary/controller/DiaryController.java
  api/src/main/java/com/lovely4k/backend/health/HealthChecker.java
  api/src/main/java/com/lovely4k/backend/member/controller/MemberController.java
  api/src/main/java/com/lovely4k/backend/member/controller/request/MemberProfileEditRequest.java
  api/src/main/java/com/lovely4k/backend/member/service/MemberService.java
  api/src/main/java/com/lovely4k/backend/member/service/request/MemberProfileEditServiceRequest.java
  api/src/main/java/com/lovely4k/backend/member/service/response/MemberProfileGetResponse.java
  api/src/main/java/com/lovely4k/backend/question/controller/QuestionController.java
  api/src/main/java/com/lovely4k/backend/question/service/QuestionQueryService.java
  api/src/main/java/com/lovely4k/backend/question/service/QuestionService.java
  api/src/main/resources/application.yaml
  api/src/main/resources/schema/schema.sql
  api/src/test/java/com/lovely4k/backend/ControllerTestSupport.java
  api/src/test/java/com/lovely4k/backend/architect/ArchTests.java
  api/src/test/java/com/lovely4k/backend/common/log/HttpAspectTest.java
  api/src/test/java/com/lovely4k/backend/couple/controller/CoupleControllerTest.java
  api/src/test/java/com/lovely4k/backend/couple/service/CoupleServiceTest.java
  api/src/test/java/com/lovely4k/backend/diary/controller/DiaryControllerTest.java
  api/src/test/java/com/lovely4k/backend/diary/service/DiaryServiceTest.java
  api/src/test/java/com/lovely4k/backend/diary/service/request/DiaryCreateRequestTest.java
  api/src/test/java/com/lovely4k/backend/member/controller/MemberControllerTest.java
  api/src/test/java/com/lovely4k/backend/member/service/MemberServiceTest.java
  api/src/test/java/com/lovely4k/backend/question/controller/QuestionControllerTest.java
  api/src/test/java/com/lovely4k/backend/question/service/QuestionQueryServiceTest.java
  api/src/test/java/com/lovely4k/backend/question/service/QuestionServiceConcurrencyTest.java
  api/src/test/java/com/lovely4k/backend/question/service/QuestionServiceTest.java
  api/src/test/java/com/lovely4k/docs/RestDocsSupport.java
  api/src/test/java/com/lovely4k/docs/couple/CoupleControllerDocsTest.java
  api/src/test/java/com/lovely4k/docs/diary/DiaryControllerDocsTest.java
  api/src/test/java/com/lovely4k/docs/member/MemberControllerDocsTest.java
  api/src/test/java/com/lovely4k/docs/question/QuestionApiDocsTest.java
  api/src/test/resources/application.yaml
  build.gradle
  model/src/main/java/com/lovely4k/backend/member/Member.java
  model/src/main/java/com/lovely4k/backend/member/Role.java
  model/src/main/java/com/lovely4k/backend/member/Sex.java
  model/src/main/java/com/lovely4k/backend/member/repository/MemberRepository.java
  model/src/test/java/com/lovely4k/backend/diary/DiaryTest.java
  model/src/test/java/com/lovely4k/backend/member/MemberTest.java
  scripts/start.sh
Labels: docs

#115 docs : 로그인 docs 작성
  api/src/docs/asciidoc/api/diary/diary-create.adoc
  api/src/docs/asciidoc/api/login/login.adoc
  api/src/docs/asciidoc/api/question/questions.adoc
  api/src/docs/asciidoc/index.adoc
  api/src/main/java/com/lovely4k/backend/member/controller/MemberController.java
  scripts/start.sh
Labels: docs

#117 refactor : 커플 초대코드 발급 http 메소드 변경
  api/src/main/java/com/lovely4k/backend/couple/controller/CoupleController.java
  api/src/test/java/com/lovely4k/backend/couple/controller/CoupleControllerTest.java
  api/src/test/java/com/lovely4k/docs/couple/CoupleControllerDocsTest.java
Labels: refactor

#118 refactor : 커플 초대코드 발급 http 메소드 변경
  api/src/docs/asciidoc/api/diary/diary-delete.adoc
  api/src/docs/asciidoc/api/diary/diary-getDetail.adoc
  api/src/docs/asciidoc/api/member/member-profile-get.adoc
  api/src/main/java/com/lovely4k/backend/couple/service/CoupleService.java
  api/src/main/java/com/lovely4k/backend/couple/service/response/CoupleProfileGetResponse.java
  api/src/test/java/com/lovely4k/backend/ControllerTestSupport.java
  api/src/test/java/com/lovely4k/backend/couple/controller/CoupleControllerTest.java
  api/src/test/java/com/lovely4k/backend/couple/service/CoupleServiceTest.java
  api/src/test/java/com/lovely4k/docs/RestDocsSupport.java
  api/src/test/java/com/lovely4k/docs/couple/CoupleControllerDocsTest.java
  api/src/test/java/com/lovely4k/docs/diary/DiaryControllerDocsTest.java
Labels: refactor

#120 feat : logback 설정 추가
  .gitignore
  api/src/main/java/com/lovely4k/backend/common/GlobalExceptionHandler.java
  api/src/main/java/com/lovely4k/backend/common/log/HttpAspect.java
  api/src/main/java/com/lovely4k/backend/common/log/HttpLogResponse.java
  api/src/main/java/com/lovely4k/backend/common/log/PrepareStatementInspector.java
  api/src/main/java/com/lovely4k/backend/common/log/SqlLogConfig.java
  api/src/main/resources/application.yaml
  api/src/main/resources/logback-spring.xml
  api/src/test/java/com/lovely4k/backend/common/log/HttpAspectTest.java
  api/src/test/java/com/lovely4k/backend/couple/controller/CoupleControllerTest.java
Labels: feat

#102 feat : calendar create
  api/src/main/java/com/lovely4k/backend/calendar/controller/CalendarController.java
  api/src/main/java/com/lovely4k/backend/calendar/controller/request/CreateCalendarRequest.java
  api/src/main/java/com/lovely4k/backend/calendar/service/CalendarCommandService.java
  api/src/main/java/com/lovely4k/backend/calendar/service/request/CreateCalendarServiceReqeust.java
  api/src/main/java/com/lovely4k/backend/calendar/service/response/CreateCalendarResponse.java
  api/src/main/resources/application.yaml
  api/src/main/resources/schema/schema.sql
  api/src/test/java/com/lovely4k/backend/ControllerTestSupport.java
  api/src/test/java/com/lovely4k/backend/calendar/controller/CalendarControllerTest.java
  api/src/test/java/com/lovely4k/backend/calendar/service/CalendarCommandServiceTest.java
  api/src/test/java/com/lovely4k/docs/calendar/CalendarApiDocsTest.java
  api/src/test/resources/application.yaml
  model/src/main/java/com/lovely4k/backend/calendar/Calendar.java
  model/src/test/java/com/lovely4k/backend/calendar/CalendarTest.java
Labels: feat

#111 Feat couple restore
  api/build.gradle
  api/src/main/java/com/lovely4k/backend/authentication/CustomSuccessHandler.java
  api/src/main/java/com/lovely4k/backend/authentication/SecurityConfig.java
  api/src/main/java/com/lovely4k/backend/common/enumvalidator/ValueOfEnumValidator.java
  api/src/main/java/com/lovely4k/backend/couple/controller/CoupleController.java
  api/src/main/java/com/lovely4k/backend/couple/service/CoupleService.java
  api/src/main/java/com/lovely4k/backend/couple/service/request/DecideReCoupleServiceRequest.java
  api/src/main/resources/schema/schema.sql
  api/src/test/java/com/lovely4k/backend/ControllerTestSupport.java
  api/src/test/java/com/lovely4k/backend/couple/controller/CoupleControllerTest.java
  api/src/test/java/com/lovely4k/backend/couple/service/CoupleServiceTest.java
  api/src/test/java/com/lovely4k/docs/RestDocsSupport.java
  api/src/test/java/com/lovely4k/docs/couple/CoupleControllerDocsTest.java
  model/src/main/java/com/lovely4k/backend/couple/Couple.java
  model/src/main/java/com/lovely4k/backend/couple/CoupleStatus.java
  model/src/main/java/com/lovely4k/backend/couple/repository/CoupleRepository.java
  model/src/main/java/com/lovely4k/backend/member/Member.java
  model/src/test/java/com/lovely4k/backend/couple/CoupleTest.java
  model/src/test/java/com/lovely4k/backend/couple/repository/CoupleRepositoryTest.java
  model/src/test/resources/calendar.sql
  model/src/test/resources/question.sql
  model/src/test/resources/test.sql
Labels: feat

#122 docs : calendar asciidoc
  api/src/docs/asciidoc/api/calendar/calendars.adoc
  api/src/docs/asciidoc/index.adoc
  api/src/main/java/com/lovely4k/backend/calendar/controller/CalendarController.java
  api/src/main/java/com/lovely4k/backend/calendar/controller/request/FindCalendarsWithDateRequest.java
  api/src/main/java/com/lovely4k/backend/calendar/service/CalendarQueryService.java
  api/src/test/java/com/lovely4k/backend/calendar/controller/CalendarControllerTest.java
  api/src/test/java/com/lovely4k/backend/calendar/service/CalendarCommandServiceTest.java
  api/src/test/java/com/lovely4k/backend/calendar/service/CalendarQueryServiceTest.java
  api/src/test/java/com/lovely4k/docs/calendar/CalendarApiDocsTest.java
  model/src/main/java/com/lovely4k/backend/calendar/Calendar.java
  model/src/main/java/com/lovely4k/backend/calendar/repository/CalendarQueryRepository.java
  model/src/main/java/com/lovely4k/backend/calendar/repository/FindCalendarsWithDateRepositoryRequest.java
  model/src/test/java/com/lovely4k/backend/calendar/repository/CalendarQueryRepositoryTest.java
Labels: refactor, docs

#123 feat : 커플 맺어졌을 때, 회원 정보가 변경되었을 때 로그아웃 없이 세션 정보 변경 기능 추가
  api/src/main/java/com/lovely4k/backend/authentication/MyOAuth2Member.java
  api/src/main/java/com/lovely4k/backend/authentication/SessionInfoUpdateHandler.java
  api/src/main/java/com/lovely4k/backend/couple/service/CoupleService.java
  api/src/main/java/com/lovely4k/backend/member/service/MemberService.java
  api/src/test/java/com/lovely4k/backend/authentication/SessionInfoUpdateHandlerTest.java
  model/src/main/java/com/lovely4k/backend/couple/CoupleCreatedEvent.java
  model/src/main/java/com/lovely4k/backend/couple/CoupleUpdatedEvent.java
  model/src/main/java/com/lovely4k/backend/member/MemberupdatedEvent.java
Labels: feat

#124 refactor : question명령 조회 분리
  api/src/main/java/com/lovely4k/backend/question/controller/QuestionController.java
  api/src/main/java/com/lovely4k/backend/question/service/QuestionQueryService.java
  api/src/main/java/com/lovely4k/backend/question/service/QuestionService.java
  api/src/main/java/com/lovely4k/backend/question/service/QuestionServiceSupporter.java
  api/src/main/java/com/lovely4k/backend/question/service/response/AnsweredQuestionResponse.java
  api/src/main/java/com/lovely4k/backend/question/service/response/DailyQuestionResponse.java
  api/src/main/java/com/lovely4k/backend/question/service/response/QuestionDetailsResponse.java
  api/src/test/java/com/lovely4k/backend/diary/service/DiaryServiceTest.java
  api/src/test/java/com/lovely4k/backend/question/service/QuestionQueryServiceTest.java
  api/src/test/java/com/lovely4k/backend/question/service/QuestionServiceSupporterTest.java
  api/src/test/java/com/lovely4k/backend/question/service/QuestionServiceTest.java
  api/src/test/java/com/lovely4k/docs/question/QuestionApiDocsTest.java
  model/src/main/java/com/lovely4k/backend/common/jpa/BaseTimeEntity.java
  model/src/main/java/com/lovely4k/backend/question/Question.java
  model/src/main/java/com/lovely4k/backend/question/repository/QuestionQueryRepository.java
  model/src/main/java/com/lovely4k/backend/question/repository/QuestionRepository.java
  model/src/main/java/com/lovely4k/backend/question/repository/response/AnsweredQuestionResponse.java
  model/src/main/java/com/lovely4k/backend/question/repository/response/DailyQuestionResponse.java
  model/src/main/java/com/lovely4k/backend/question/repository/response/QuestionResponse.java
  model/src/test/java/com/lovely4k/backend/QueryTestSupport.java
  model/src/test/java/com/lovely4k/backend/calendar/repository/CalendarQueryRepositoryTest.java
  model/src/test/java/com/lovely4k/backend/diary/DiaryRepositoryAdapterTest.java
  model/src/test/java/com/lovely4k/backend/diary/QDiaryRepositoryTest.java
  model/src/test/java/com/lovely4k/backend/question/QuestionTest.java
  model/src/test/java/com/lovely4k/backend/question/repository/QuestionFormRepositoryTest.java
  model/src/test/java/com/lovely4k/backend/question/repository/QuestionQueryRepositoryTest.java
  model/src/test/java/com/lovely4k/backend/question/repository/QuestionRepositoryTest.java
  model/src/test/resources/application-query.yaml
  model/src/test/resources/questions/answeredQuestion.sql
  model/src/test/resources/questions/dailyQuestion.sql
  model/src/test/resources/questions/question.sql
  model/src/test/resources/questions/questionForm.sql
Labels: refactor

#125 refactor : 2.2배포 관련 일부 코드 수정
  api/build.gradle
  api/src/docs/asciidoc/api/login/login.adoc
  api/src/main/resources/schema/schema.sql
Labels: release

#127 fix : logback ec2 경로 수정
  api/src/main/resources/logback-spring.xml
Labels: release

#128 fix : logback ec2 경로 수정
  api/src/main/resources/logback-spring.xml
Labels: release

#131 refactor : 로그인 시 redirect url 변경 및 테스트 support code 추가
  api/src/main/java/com/lovely4k/backend/authentication/CustomSuccessHandler.java
  api/src/main/java/com/lovely4k/backend/authentication/SecurityConfig.java
  api/src/test/java/com/lovely4k/backend/ControllerTestSupport.java
  api/src/test/resources/application.yaml
Labels: refactor

#129 Refactor couple
  api/src/main/java/com/lovely4k/backend/couple/controller/CoupleController.java
  api/src/main/java/com/lovely4k/backend/couple/service/CoupleService.java
  api/src/main/java/com/lovely4k/backend/couple/service/response/CoupleProfileGetResponse.java
  model/src/main/java/com/lovely4k/backend/couple/Couple.java
  model/src/main/java/com/lovely4k/backend/couple/repository/CoupleQueryRepository.java
  model/src/main/java/com/lovely4k/backend/couple/repository/response/FindCoupleProfileResponse.java
  model/src/test/java/com/lovely4k/backend/couple/CoupleTest.java
  model/src/test/java/com/lovely4k/backend/couple/repository/CoupleQueryRepositoryTest.java
  model/src/test/resources/calendar.sql
  model/src/test/resources/test.sql
Labels: refactor

#130 refactor : calendar 응답 필드 ownerId 추가, question session으로부터 정보 얻어오기 추가
  api/src/main/java/com/lovely4k/backend/calendar/service/response/FindCalendarsWithDateServiceResponse.java
  api/src/main/java/com/lovely4k/backend/calendar/service/response/FindRecentCalendarsServiceResponse.java
  api/src/main/java/com/lovely4k/backend/question/controller/QuestionController.java
  api/src/main/java/com/lovely4k/backend/question/controller/request/AnsweredQuestionParamRequest.java
  api/src/main/resources/schema/schema.sql
  api/src/test/java/com/lovely4k/backend/calendar/service/CalendarQueryServiceTest.java
  api/src/test/java/com/lovely4k/docs/calendar/CalendarApiDocsTest.java
  model/src/main/java/com/lovely4k/backend/calendar/Calendar.java
  model/src/main/java/com/lovely4k/backend/calendar/repository/CalendarQueryRepository.java
  model/src/main/java/com/lovely4k/backend/calendar/repository/response/FindCalendarsWithDateResponse.java
  model/src/main/java/com/lovely4k/backend/calendar/repository/response/FindRecentCalendarsResponse.java
  model/src/test/java/com/lovely4k/backend/calendar/repository/CalendarQueryRepositoryTest.java
  model/src/test/resources/calendar.sql
Labels: refactor

#132 refactor : 로그 포맷팅 변경
  .gitignore
  api/src/main/java/com/lovely4k/backend/common/log/HttpLogResponse.java
Labels: refactor

#133 Release 2.3
  .gitignore
  api/src/main/java/com/lovely4k/backend/authentication/CustomSuccessHandler.java
  api/src/main/java/com/lovely4k/backend/authentication/SecurityConfig.java
  api/src/main/java/com/lovely4k/backend/calendar/service/response/FindCalendarsWithDateServiceResponse.java
  api/src/main/java/com/lovely4k/backend/calendar/service/response/FindRecentCalendarsServiceResponse.java
  api/src/main/java/com/lovely4k/backend/common/log/HttpLogResponse.java
  api/src/main/java/com/lovely4k/backend/couple/controller/CoupleController.java
  api/src/main/java/com/lovely4k/backend/couple/service/CoupleService.java
  api/src/main/java/com/lovely4k/backend/couple/service/response/CoupleProfileGetResponse.java
  api/src/main/java/com/lovely4k/backend/question/controller/QuestionController.java
  api/src/main/java/com/lovely4k/backend/question/controller/request/AnsweredQuestionParamRequest.java
  api/src/main/resources/schema/schema.sql
  api/src/test/java/com/lovely4k/backend/ControllerTestSupport.java
  api/src/test/java/com/lovely4k/backend/calendar/service/CalendarQueryServiceTest.java
  api/src/test/java/com/lovely4k/docs/calendar/CalendarApiDocsTest.java
  api/src/test/resources/application.yaml
  model/src/main/java/com/lovely4k/backend/calendar/Calendar.java
  model/src/main/java/com/lovely4k/backend/calendar/repository/CalendarQueryRepository.java
  model/src/main/java/com/lovely4k/backend/calendar/repository/response/FindCalendarsWithDateResponse.java
  model/src/main/java/com/lovely4k/backend/calendar/repository/response/FindRecentCalendarsResponse.java
  model/src/main/java/com/lovely4k/backend/couple/Couple.java
  model/src/main/java/com/lovely4k/backend/couple/repository/CoupleQueryRepository.java
  model/src/main/java/com/lovely4k/backend/couple/repository/response/FindCoupleProfileResponse.java
  model/src/test/java/com/lovely4k/backend/calendar/repository/CalendarQueryRepositoryTest.java
  model/src/test/java/com/lovely4k/backend/couple/CoupleTest.java
  model/src/test/java/com/lovely4k/backend/couple/repository/CoupleQueryRepositoryTest.java
  model/src/test/resources/calendar.sql
  model/src/test/resources/test.sql
Labels: release

#135 feat : session -> JWT 전략 변경[#134]
  api/build.gradle
  api/src/main/java/com/lovely4k/backend/authentication/CustomSuccessHandler.java
  api/src/main/java/com/lovely4k/backend/authentication/SessionInfoUpdateHandler.java
  api/src/main/java/com/lovely4k/backend/authentication/exception/AccessDeniedHandlerException.java
  api/src/main/java/com/lovely4k/backend/authentication/exception/AuthenticationEntryPointException.java
  api/src/main/java/com/lovely4k/backend/authentication/token/JwtFilter.java
  api/src/main/java/com/lovely4k/backend/authentication/token/SecurityConfig.java
  api/src/main/java/com/lovely4k/backend/authentication/token/TokenDto.java
  api/src/main/java/com/lovely4k/backend/authentication/token/TokenProvider.java
  api/src/main/java/com/lovely4k/backend/authentication/token/UserDetailsImpl.java
  api/src/main/java/com/lovely4k/backend/authentication/token/UserDetailsServiceImpl.java
  api/src/main/java/com/lovely4k/backend/common/sessionuser/MemberInfo.java
  api/src/main/java/com/lovely4k/backend/couple/service/CoupleService.java
  api/src/main/java/com/lovely4k/backend/member/controller/MemberController.java
  api/src/main/java/com/lovely4k/backend/member/service/MemberService.java
  api/src/main/resources/application-local.yaml
  api/src/main/resources/schema/schema.sql
  api/src/test/java/com/lovely4k/backend/ControllerTestSupport.java
  api/src/test/java/com/lovely4k/backend/authentication/SessionInfoUpdateHandlerTest.java
  api/src/test/resources/application.yaml
  model/src/main/java/com/lovely4k/backend/authentication/RefreshToken.java
  model/src/main/java/com/lovely4k/backend/authentication/RefreshTokenRepository.java
  model/src/main/java/com/lovely4k/backend/couple/CoupleCreatedEvent.java
  model/src/main/java/com/lovely4k/backend/couple/CoupleUpdatedEvent.java
  model/src/main/java/com/lovely4k/backend/member/Member.java
  model/src/main/java/com/lovely4k/backend/member/MemberupdatedEvent.java
  model/src/main/java/com/lovely4k/backend/member/repository/MemberRepository.java
  model/src/test/java/com/lovely4k/backend/question/repository/QuestionFormRepositoryTest.java
  model/src/test/java/com/lovely4k/backend/question/repository/QuestionQueryRepositoryTest.java
  model/src/test/resources/application.yaml
  model/src/test/resources/init.sql
  model/src/test/resources/questions/question.sql
  model/src/test/resources/questions/questionForm.sql
  model/src/test/resources/test.sql
Labels: feat

#136 Release 2.4
  api/build.gradle
  api/src/main/java/com/lovely4k/backend/authentication/CustomSuccessHandler.java
  api/src/main/java/com/lovely4k/backend/authentication/SessionInfoUpdateHandler.java
  api/src/main/java/com/lovely4k/backend/authentication/exception/AccessDeniedHandlerException.java
  api/src/main/java/com/lovely4k/backend/authentication/exception/AuthenticationEntryPointException.java
  api/src/main/java/com/lovely4k/backend/authentication/token/JwtFilter.java
  api/src/main/java/com/lovely4k/backend/authentication/token/SecurityConfig.java
  api/src/main/java/com/lovely4k/backend/authentication/token/TokenDto.java
  api/src/main/java/com/lovely4k/backend/authentication/token/TokenProvider.java
  api/src/main/java/com/lovely4k/backend/authentication/token/UserDetailsImpl.java
  api/src/main/java/com/lovely4k/backend/authentication/token/UserDetailsServiceImpl.java
  api/src/main/java/com/lovely4k/backend/common/sessionuser/MemberInfo.java
  api/src/main/java/com/lovely4k/backend/couple/service/CoupleService.java
  api/src/main/java/com/lovely4k/backend/member/controller/MemberController.java
  api/src/main/java/com/lovely4k/backend/member/service/MemberService.java
  api/src/main/resources/application-local.yaml
  api/src/main/resources/schema/schema.sql
  api/src/test/java/com/lovely4k/backend/ControllerTestSupport.java
  api/src/test/java/com/lovely4k/backend/authentication/SessionInfoUpdateHandlerTest.java
  api/src/test/resources/application.yaml
  model/src/main/java/com/lovely4k/backend/authentication/RefreshToken.java
  model/src/main/java/com/lovely4k/backend/authentication/RefreshTokenRepository.java
  model/src/main/java/com/lovely4k/backend/couple/CoupleCreatedEvent.java
  model/src/main/java/com/lovely4k/backend/couple/CoupleUpdatedEvent.java
  model/src/main/java/com/lovely4k/backend/member/Member.java
  model/src/main/java/com/lovely4k/backend/member/MemberupdatedEvent.java
  model/src/main/java/com/lovely4k/backend/member/repository/MemberRepository.java
  model/src/test/java/com/lovely4k/backend/question/repository/QuestionFormRepositoryTest.java
  model/src/test/java/com/lovely4k/backend/question/repository/QuestionQueryRepositoryTest.java
  model/src/test/resources/application.yaml
  model/src/test/resources/init.sql
  model/src/test/resources/questions/question.sql
  model/src/test/resources/questions/questionForm.sql
  model/src/test/resources/test.sql
Labels: release

#139 refactor : 답변한 질문 목록 조회 오류 수정(id보다 작은 값으로 페이징 처리 되도록 수정)
  api/src/docs/asciidoc/api/question/questions.adoc
  api/src/main/java/com/lovely4k/backend/question/controller/request/AnsweredQuestionParamRequest.java
  api/src/test/java/com/lovely4k/docs/question/QuestionApiDocsTest.java
  model/src/main/java/com/lovely4k/backend/question/repository/QuestionQueryRepository.java
  model/src/test/java/com/lovely4k/backend/question/repository/QuestionQueryRepositoryTest.java
Labels: refactor

#140 Release 2.5
  .github/workflows/sonarcloud.yml
  api/build.gradle
  api/src/docs/asciidoc/api/diary/diary-edit.adoc
  api/src/docs/asciidoc/api/diary/diary-getListByMarker.adoc
  api/src/docs/asciidoc/api/diary/diary-getListInGrid.adoc
  api/src/docs/asciidoc/api/question/questions.adoc
  api/src/docs/asciidoc/index.adoc
  api/src/main/java/com/lovely4k/backend/diary/controller/DiaryController.java
  api/src/main/java/com/lovely4k/backend/diary/controller/request/DiaryEditRequest.java
  api/src/main/java/com/lovely4k/backend/diary/controller/request/WebDiaryCreateRequest.java
  api/src/main/java/com/lovely4k/backend/diary/controller/request/WebDiaryEditRequest.java
  api/src/main/java/com/lovely4k/backend/diary/service/DiaryService.java
  api/src/main/java/com/lovely4k/backend/diary/service/request/DiaryCreateRequest.java
  api/src/main/java/com/lovely4k/backend/diary/service/request/DiaryEditRequest.java
  api/src/main/java/com/lovely4k/backend/diary/service/response/DiaryGridResponse.java
  api/src/main/java/com/lovely4k/backend/diary/service/response/DiaryListByMarkerResponse.java
  api/src/main/java/com/lovely4k/backend/diary/service/response/DiaryListInGridResponse.java
  api/src/main/java/com/lovely4k/backend/diary/service/response/DiaryListResponse.java
  api/src/main/java/com/lovely4k/backend/diary/service/response/DiaryMarkerResponse.java
  api/src/main/java/com/lovely4k/backend/question/controller/QuestionController.java
  api/src/main/java/com/lovely4k/backend/question/controller/request/AnsweredQuestionParamRequest.java
  api/src/main/java/com/lovely4k/backend/question/service/QuestionQueryService.java
  api/src/main/resources/schema/schema.sql
  api/src/test/java/com/lovely4k/backend/diary/controller/DiaryControllerTest.java
  api/src/test/java/com/lovely4k/backend/diary/service/DiaryServiceTest.java
  api/src/test/java/com/lovely4k/backend/diary/service/request/DiaryCreateRequestTest.java
  api/src/test/java/com/lovely4k/backend/question/controller/QuestionControllerTest.java
  api/src/test/java/com/lovely4k/backend/question/service/QuestionQueryServiceForGameTest.java
  api/src/test/java/com/lovely4k/docs/diary/DiaryControllerDocsTest.java
  api/src/test/java/com/lovely4k/docs/diary/MockDiaryCreateRequest.java
  api/src/test/java/com/lovely4k/docs/diary/MockDiaryEditRequest.java
  api/src/test/java/com/lovely4k/docs/question/QuestionApiDocsTest.java
  model/src/main/java/com/lovely4k/backend/diary/Diary.java
  model/src/main/java/com/lovely4k/backend/diary/DiaryRepository.java
  model/src/main/java/com/lovely4k/backend/diary/DiaryRepositoryAdapter.java
  model/src/main/java/com/lovely4k/backend/diary/Photos.java
  model/src/main/java/com/lovely4k/backend/location/Location.java
  model/src/main/java/com/lovely4k/backend/question/repository/QuestionQueryRepository.java
  model/src/main/java/com/lovely4k/backend/question/repository/response/QuestionGameResponse.java
  model/src/test/java/com/lovely4k/backend/diary/DiaryRepositoryAdapterTest.java
  model/src/test/java/com/lovely4k/backend/diary/DiaryRepositoryTest.java
  model/src/test/java/com/lovely4k/backend/diary/DiaryTest.java
  model/src/test/java/com/lovely4k/backend/diary/PhotosTest.java
  model/src/test/java/com/lovely4k/backend/diary/QDiaryRepositoryTest.java
  model/src/test/java/com/lovely4k/backend/location/LocationTest.java
  model/src/test/java/com/lovely4k/backend/question/repository/QuestionQueryRepositoryTest.java
  model/src/test/resources/questions/findQuestionGame.sql
Labels: release

#141 refactor : 조회 오류 수정 web request에서 to from 파싱이 잘못 됨
  api/src/main/java/com/lovely4k/backend/authentication/token/JwtFilter.java
  api/src/main/java/com/lovely4k/backend/calendar/controller/request/FindCalendarsWithDateRequest.java
  api/src/main/java/com/lovely4k/backend/calendar/service/CalendarCommandService.java
  api/src/main/java/com/lovely4k/backend/calendar/service/request/CreateCalendarServiceReqeust.java
  api/src/main/java/com/lovely4k/backend/calendar/service/response/FindCalendarsWithDateServiceResponse.java
  api/src/main/resources/schema/schema.sql
  model/src/main/java/com/lovely4k/backend/calendar/Calendar.java
  model/src/test/java/com/lovely4k/backend/calendar/CalendarTest.java
Labels: refactor

#142 docs : readme 작성
  README.md
  api/src/main/java/com/lovely4k/backend/authentication/token/JwtFilter.java
  api/src/main/java/com/lovely4k/backend/authentication/token/TokenProvider.java
  api/src/main/java/com/lovely4k/backend/calendar/controller/request/FindCalendarsWithDateRequest.java
  api/src/main/java/com/lovely4k/backend/calendar/service/CalendarCommandService.java
  api/src/main/java/com/lovely4k/backend/calendar/service/request/CreateCalendarServiceReqeust.java
  api/src/main/java/com/lovely4k/backend/calendar/service/response/FindCalendarsWithDateServiceResponse.java
  api/src/main/resources/schema/schema.sql
  etc/index.html
  model/src/main/java/com/lovely4k/backend/calendar/Calendar.java
  model/src/test/java/com/lovely4k/backend/calendar/CalendarTest.java
Labels: docs

#144 refactor : 동성 커플일 경우 프로필 조회를 위한 쿼리 수정
  api/src/test/java/com/lovely4k/backend/couple/service/CoupleServiceTest.java
  model/src/main/java/com/lovely4k/backend/couple/repository/CoupleQueryRepository.java
Labels: refactor

#146 Release 2.5
  README.md
  api/src/main/java/com/lovely4k/backend/diary/controller/DiaryController.java
  api/src/test/java/com/lovely4k/backend/couple/service/CoupleServiceTest.java
  model/src/main/java/com/lovely4k/backend/couple/repository/CoupleQueryRepository.java
Labels: release

#143 docs : readme 작성
  README.md
  api/src/main/java/com/lovely4k/backend/authentication/token/JwtFilter.java
  api/src/main/java/com/lovely4k/backend/authentication/token/TokenProvider.java
  api/src/main/java/com/lovely4k/backend/calendar/controller/request/FindCalendarsWithDateRequest.java
  api/src/main/java/com/lovely4k/backend/calendar/service/CalendarCommandService.java
  api/src/main/java/com/lovely4k/backend/calendar/service/request/CreateCalendarServiceReqeust.java
  api/src/main/java/com/lovely4k/backend/calendar/service/response/FindCalendarsWithDateServiceResponse.java
  api/src/main/java/com/lovely4k/backend/diary/controller/DiaryController.java
  api/src/main/resources/schema/schema.sql
  api/src/test/java/com/lovely4k/backend/couple/service/CoupleServiceTest.java
  etc/index.html
  model/src/main/java/com/lovely4k/backend/calendar/Calendar.java
  model/src/main/java/com/lovely4k/backend/couple/repository/CoupleQueryRepository.java
  model/src/test/java/com/lovely4k/backend/calendar/CalendarTest.java
Labels: docs

#148 refactor : diary 목록 조회시 응답 목록 변경
  api/src/main/java/com/lovely4k/backend/diary/service/response/DiaryListResponse.java
  api/src/test/java/com/lovely4k/docs/diary/DiaryControllerDocsTest.java
Labels: refactor

#147 feat : Event 및 @Retryable 적용 [#75]
  api/src/main/java/com/lovely4k/backend/common/config/AsyncConfig.java
  api/src/main/java/com/lovely4k/backend/common/event/Events.java
  api/src/main/java/com/lovely4k/backend/common/event/EventsConfiguration.java
  api/src/main/java/com/lovely4k/backend/couple/IncreaseTemperatureEvent.java
  api/src/main/java/com/lovely4k/backend/couple/IncreaseTemperatureEventHandler.java
  api/src/main/java/com/lovely4k/backend/couple/service/CoupleService.java
  api/src/main/java/com/lovely4k/backend/couple/service/IncreaseTemperatureFacade.java
  api/src/main/java/com/lovely4k/backend/diary/service/DiaryService.java
  api/src/main/java/com/lovely4k/backend/question/service/QuestionService.java
  api/src/test/java/com/lovely4k/backend/architect/ArchTests.java
  api/src/test/java/com/lovely4k/backend/couple/IncreaseTemperatureEventHandlerTest.java
  api/src/test/java/com/lovely4k/backend/couple/service/CoupleServiceConcurrencyTest.java
  api/src/test/java/com/lovely4k/backend/couple/service/CoupleServiceRetryableTest.java
  api/src/test/java/com/lovely4k/backend/couple/service/IncreaseTemperatureFacadeTest.java
  api/src/test/java/com/lovely4k/backend/question/service/QuestionServiceTest.java
Labels: feat, refactor

#150 refactor : questionSex 필드가 아닌 couple 테이블의 boy_id, girl_id 기반으로 답변 방식 변경
  api/src/docs/asciidoc/api/question/questions.adoc
  api/src/main/java/com/lovely4k/backend/common/ApiResponse.java
  api/src/main/java/com/lovely4k/backend/question/controller/QuestionController.java
  api/src/main/java/com/lovely4k/backend/question/service/QuestionQueryService.java
  api/src/main/java/com/lovely4k/backend/question/service/QuestionService.java
  api/src/main/java/com/lovely4k/backend/question/service/QuestionServiceSupporter.java
  api/src/test/java/com/lovely4k/backend/question/service/QuestionQueryServiceForGameTest.java
  api/src/test/java/com/lovely4k/backend/question/service/QuestionQueryServiceTest.java
  api/src/test/java/com/lovely4k/backend/question/service/QuestionServiceConcurrencyTest.java
  api/src/test/java/com/lovely4k/backend/question/service/QuestionServiceSupporterTest.java
  api/src/test/java/com/lovely4k/backend/question/service/QuestionServiceTest.java
  api/src/test/java/com/lovely4k/docs/question/QuestionApiDocsTest.java
  model/src/main/java/com/lovely4k/backend/authentication/RefreshToken.java
  model/src/main/java/com/lovely4k/backend/question/Question.java
  model/src/main/java/com/lovely4k/backend/question/repository/QuestionQueryRepository.java
  model/src/test/java/com/lovely4k/backend/question/QuestionTest.java
  model/src/test/java/com/lovely4k/backend/question/repository/QuestionQueryRepositoryTest.java
  model/src/test/resources/questions/findQuestionGame.sql
  model/src/test/resources/questions/question.sql
Labels: refactor

#152 release : 2.6
  api/src/docs/asciidoc/api/question/questions.adoc
  api/src/main/java/com/lovely4k/backend/common/ApiResponse.java
  api/src/main/java/com/lovely4k/backend/common/config/AsyncConfig.java
  api/src/main/java/com/lovely4k/backend/common/event/Events.java
  api/src/main/java/com/lovely4k/backend/common/event/EventsConfiguration.java
  api/src/main/java/com/lovely4k/backend/couple/IncreaseTemperatureEvent.java
  api/src/main/java/com/lovely4k/backend/couple/IncreaseTemperatureEventHandler.java
  api/src/main/java/com/lovely4k/backend/couple/service/CoupleService.java
  api/src/main/java/com/lovely4k/backend/couple/service/IncreaseTemperatureFacade.java
  api/src/main/java/com/lovely4k/backend/diary/service/DiaryService.java
  api/src/main/java/com/lovely4k/backend/diary/service/response/DiaryListResponse.java
  api/src/main/java/com/lovely4k/backend/question/controller/QuestionController.java
  api/src/main/java/com/lovely4k/backend/question/service/QuestionQueryService.java
  api/src/main/java/com/lovely4k/backend/question/service/QuestionService.java
  api/src/main/java/com/lovely4k/backend/question/service/QuestionServiceSupporter.java
  api/src/test/java/com/lovely4k/backend/architect/ArchTests.java
  api/src/test/java/com/lovely4k/backend/couple/IncreaseTemperatureEventHandlerTest.java
  api/src/test/java/com/lovely4k/backend/couple/service/CoupleServiceConcurrencyTest.java
  api/src/test/java/com/lovely4k/backend/couple/service/CoupleServiceRetryableTest.java
  api/src/test/java/com/lovely4k/backend/couple/service/IncreaseTemperatureFacadeTest.java
  api/src/test/java/com/lovely4k/backend/question/service/QuestionQueryServiceForGameTest.java
  api/src/test/java/com/lovely4k/backend/question/service/QuestionQueryServiceTest.java
  api/src/test/java/com/lovely4k/backend/question/service/QuestionServiceConcurrencyTest.java
  api/src/test/java/com/lovely4k/backend/question/service/QuestionServiceSupporterTest.java
  api/src/test/java/com/lovely4k/backend/question/service/QuestionServiceTest.java
  api/src/test/java/com/lovely4k/docs/diary/DiaryControllerDocsTest.java
  api/src/test/java/com/lovely4k/docs/question/QuestionApiDocsTest.java
  model/src/main/java/com/lovely4k/backend/authentication/RefreshToken.java
  model/src/main/java/com/lovely4k/backend/question/Question.java
  model/src/main/java/com/lovely4k/backend/question/repository/QuestionQueryRepository.java
  model/src/test/java/com/lovely4k/backend/question/QuestionTest.java
  model/src/test/java/com/lovely4k/backend/question/repository/QuestionQueryRepositoryTest.java
  model/src/test/resources/questions/findQuestionGame.sql
  model/src/test/resources/questions/question.sql
Labels: release

#153 refactor : 최근 일정 조회 없을 시 빈객체 주기(프론트 요구사항 반영)
  api/src/main/java/com/lovely4k/backend/calendar/service/response/FindRecentCalendarsServiceResponse.java
Labels: refactor

#154 refactor : diary
  api/build.gradle
  api/src/docs/asciidoc/index.adoc
  api/src/main/java/com/lovely4k/backend/diary/controller/DiaryController.java
  api/src/main/java/com/lovely4k/backend/diary/service/DiaryService.java
  api/src/main/java/com/lovely4k/backend/diary/service/response/DiaryDetailResponse.java
  api/src/main/java/com/lovely4k/backend/diary/service/response/DiaryListByMarkerResponse.java
  api/src/test/java/com/lovely4k/backend/diary/service/DiaryServiceTest.java
  api/src/test/java/com/lovely4k/docs/diary/DiaryControllerDocsTest.java
  model/src/main/java/com/lovely4k/backend/member/Sex.java
Labels: refactor

#156 Release 2.7
  api/build.gradle
  api/src/docs/asciidoc/index.adoc
  api/src/main/java/com/lovely4k/backend/calendar/service/response/FindRecentCalendarsServiceResponse.java
  api/src/main/java/com/lovely4k/backend/diary/controller/DiaryController.java
  api/src/main/java/com/lovely4k/backend/diary/service/DiaryService.java
  api/src/main/java/com/lovely4k/backend/diary/service/response/DiaryDetailResponse.java
  api/src/main/java/com/lovely4k/backend/diary/service/response/DiaryListByMarkerResponse.java
  api/src/test/java/com/lovely4k/backend/diary/service/DiaryServiceTest.java
  api/src/test/java/com/lovely4k/docs/diary/DiaryControllerDocsTest.java
  model/src/main/java/com/lovely4k/backend/member/Sex.java
Labels: release

#157 refactor : form-data가 쿼리 파라미터에 들어가기 때문에 로그 포맷팅 형식 변경
  api/src/main/java/com/lovely4k/backend/common/log/HttpLogResponse.java
Labels: refactor

#158 release 2.7
  api/src/main/java/com/lovely4k/backend/common/log/HttpLogResponse.java
Labels: release

#159 Release 2.7
  api/src/main/java/com/lovely4k/backend/common/log/HttpLogResponse.java
Labels: release

#160 refactor : 로그 포맷팅 형식 재변경
  api/src/main/java/com/lovely4k/backend/common/log/HttpLogResponse.java
Labels: refactor

#161 refactor : front 요구사항 반영
  api/src/main/java/com/lovely4k/backend/diary/controller/DiaryController.java
  api/src/main/java/com/lovely4k/backend/diary/controller/request/WebDiaryEditRequest.java
  api/src/main/java/com/lovely4k/backend/diary/service/DiaryService.java
  api/src/main/java/com/lovely4k/backend/diary/service/request/DiaryEditRequest.java
  api/src/test/java/com/lovely4k/backend/diary/service/DiaryServiceTest.java
  api/src/test/java/com/lovely4k/docs/diary/DiaryControllerDocsTest.java
  api/src/test/java/com/lovely4k/docs/diary/MockDiaryEditRequest.java
  model/src/main/java/com/lovely4k/backend/diary/Diary.java
  model/src/test/java/com/lovely4k/backend/diary/DiaryTest.java
Labels: refactor

#162 Release 2.8
  api/src/main/java/com/lovely4k/backend/common/log/HttpLogResponse.java
  api/src/main/java/com/lovely4k/backend/diary/controller/DiaryController.java
  api/src/main/java/com/lovely4k/backend/diary/controller/request/WebDiaryEditRequest.java
  api/src/main/java/com/lovely4k/backend/diary/service/DiaryService.java
  api/src/main/java/com/lovely4k/backend/diary/service/request/DiaryEditRequest.java
  api/src/test/java/com/lovely4k/backend/diary/service/DiaryServiceTest.java
  api/src/test/java/com/lovely4k/docs/diary/DiaryControllerDocsTest.java
  api/src/test/java/com/lovely4k/docs/diary/MockDiaryEditRequest.java
  model/src/main/java/com/lovely4k/backend/diary/Diary.java
  model/src/test/java/com/lovely4k/backend/diary/DiaryTest.java
Labels: release

#163 docs : 커플 복원 / 끊기 관련 api 문서 작성
  api/src/docs/asciidoc/api/couple/couple-delete.adoc
  api/src/docs/asciidoc/api/couple/couple-recouple.adoc
  api/src/docs/asciidoc/index.adoc
  api/src/main/java/com/lovely4k/backend/couple/controller/CoupleController.java
  api/src/test/java/com/lovely4k/docs/couple/CoupleControllerDocsTest.java
Labels: docs

#164 refactor : calendar 응답 boy, girl이 아닌 my, opponent로 변경
  api/src/main/java/com/lovely4k/backend/authentication/token/SecurityConfig.java
  api/src/main/java/com/lovely4k/backend/calendar/controller/CalendarController.java
  api/src/main/java/com/lovely4k/backend/calendar/service/CalendarQueryService.java
  api/src/main/java/com/lovely4k/backend/calendar/service/response/FindCalendarsWithDateServiceResponse.java
  api/src/main/java/com/lovely4k/backend/calendar/service/response/FindRecentCalendarsServiceResponse.java
  api/src/main/java/com/lovely4k/backend/common/config/WebConfig.java
  api/src/main/java/com/lovely4k/backend/question/controller/request/AnsweredQuestionParamRequest.java
  api/src/test/java/com/lovely4k/backend/calendar/service/CalendarQueryServiceTest.java
  api/src/test/java/com/lovely4k/docs/calendar/CalendarApiDocsTest.java
  model/src/main/java/com/lovely4k/backend/calendar/repository/CalendarQueryRepository.java
  model/src/main/java/com/lovely4k/backend/calendar/repository/response/FindCalendarsWithDateResponse.java
  model/src/main/java/com/lovely4k/backend/calendar/repository/response/FindRecentCalendarsResponse.java
  model/src/test/java/com/lovely4k/backend/calendar/repository/CalendarQueryRepositoryTest.java
Labels: refactor

#165 Refactor diary
  api/src/main/java/com/lovely4k/backend/common/imageuploader/AWSS3Uploader.java
  api/src/main/java/com/lovely4k/backend/diary/service/DiaryImageUploader.java
  api/src/main/java/com/lovely4k/backend/diary/service/DiaryService.java
  api/src/main/java/com/lovely4k/backend/diary/service/response/DiaryListResponse.java
  api/src/test/java/com/lovely4k/backend/diary/service/DiaryServiceTest.java
  api/src/test/java/com/lovely4k/docs/diary/DiaryControllerDocsTest.java
  api/src/test/resources/application.yaml
Labels: feat, refactor

#167 Release 2.8
  api/src/docs/asciidoc/api/couple/couple-delete.adoc
  api/src/docs/asciidoc/api/couple/couple-recouple.adoc
  api/src/docs/asciidoc/index.adoc
  api/src/main/java/com/lovely4k/backend/authentication/token/SecurityConfig.java
  api/src/main/java/com/lovely4k/backend/calendar/controller/CalendarController.java
  api/src/main/java/com/lovely4k/backend/calendar/service/CalendarQueryService.java
  api/src/main/java/com/lovely4k/backend/calendar/service/response/FindCalendarsWithDateServiceResponse.java
  api/src/main/java/com/lovely4k/backend/calendar/service/response/FindRecentCalendarsServiceResponse.java
  api/src/main/java/com/lovely4k/backend/common/config/WebConfig.java
  api/src/main/java/com/lovely4k/backend/common/imageuploader/AWSS3Uploader.java
  api/src/main/java/com/lovely4k/backend/couple/controller/CoupleController.java
  api/src/main/java/com/lovely4k/backend/diary/service/DiaryImageUploader.java
  api/src/main/java/com/lovely4k/backend/diary/service/DiaryService.java
  api/src/main/java/com/lovely4k/backend/diary/service/response/DiaryListResponse.java
  api/src/main/java/com/lovely4k/backend/question/controller/request/AnsweredQuestionParamRequest.java
  api/src/test/java/com/lovely4k/backend/calendar/service/CalendarQueryServiceTest.java
  api/src/test/java/com/lovely4k/backend/diary/service/DiaryServiceTest.java
  api/src/test/java/com/lovely4k/docs/calendar/CalendarApiDocsTest.java
  api/src/test/java/com/lovely4k/docs/couple/CoupleControllerDocsTest.java
  api/src/test/java/com/lovely4k/docs/diary/DiaryControllerDocsTest.java
  api/src/test/resources/application.yaml
  model/src/main/java/com/lovely4k/backend/calendar/repository/CalendarQueryRepository.java
  model/src/main/java/com/lovely4k/backend/calendar/repository/response/FindCalendarsWithDateResponse.java
  model/src/main/java/com/lovely4k/backend/calendar/repository/response/FindRecentCalendarsResponse.java
  model/src/test/java/com/lovely4k/backend/calendar/repository/CalendarQueryRepositoryTest.java
Labels: release

#168 feat : 다이어리 다중 삭제 API 추가
  api/src/docs/asciidoc/api/diary/diary-delete-list.adoc
  api/src/docs/asciidoc/api/diary/diary-delete.adoc
  api/src/docs/asciidoc/api/diary/diary-getListInGrid.adoc
  api/src/docs/asciidoc/api/login/login.adoc
  api/src/docs/asciidoc/index.adoc
  api/src/main/java/com/lovely4k/backend/diary/controller/DiaryController.java
  api/src/main/java/com/lovely4k/backend/diary/controller/request/DiaryDeleteRequest.java
  api/src/main/java/com/lovely4k/backend/diary/service/DiaryService.java
  api/src/test/java/com/lovely4k/backend/diary/service/DiaryServiceTest.java
  api/src/test/java/com/lovely4k/docs/diary/DiaryControllerDocsTest.java
  model/src/main/java/com/lovely4k/backend/diary/DiaryRepositoryAdapter.java
Labels: feat

#169 Release 2.9
  api/src/docs/asciidoc/api/diary/diary-delete-list.adoc
  api/src/docs/asciidoc/api/diary/diary-delete.adoc
  api/src/docs/asciidoc/api/diary/diary-getListInGrid.adoc
  api/src/docs/asciidoc/api/login/login.adoc
  api/src/docs/asciidoc/index.adoc
  api/src/main/java/com/lovely4k/backend/diary/controller/DiaryController.java
  api/src/main/java/com/lovely4k/backend/diary/controller/request/DiaryDeleteRequest.java
  api/src/main/java/com/lovely4k/backend/diary/service/DiaryService.java
  api/src/test/java/com/lovely4k/backend/diary/service/DiaryServiceTest.java
  api/src/test/java/com/lovely4k/docs/diary/DiaryControllerDocsTest.java
  model/src/main/java/com/lovely4k/backend/diary/DiaryRepositoryAdapter.java
Labels: release

#170 feat : 사랑의 온도 조회 기능 추가
  api/src/docs/asciidoc/api/couple/couple-temperature.adoc
  api/src/docs/asciidoc/index.adoc
  api/src/main/java/com/lovely4k/backend/couple/controller/CoupleController.java
  api/src/main/java/com/lovely4k/backend/couple/service/CoupleService.java
  api/src/main/java/com/lovely4k/backend/couple/service/response/CoupleTemperatureResponse.java
  api/src/test/java/com/lovely4k/backend/couple/service/CoupleServiceTest.java
  api/src/test/java/com/lovely4k/docs/couple/CoupleControllerDocsTest.java
Labels: feat

#171 fix : question 조회시 시간을 제외하고 날짜만 비교해서 조회, 비로그인 예외 추가
  api/src/main/java/com/lovely4k/backend/common/sessionuser/LoginUserArgumentResolver.java
  api/src/main/java/com/lovely4k/backend/question/service/QuestionValidator.java
  api/src/main/resources/schema/schema.sql
  api/src/test/java/com/lovely4k/backend/ControllerTestSupport.java
  model/src/main/java/com/lovely4k/backend/question/repository/QuestionQueryRepository.java
  model/src/test/java/com/lovely4k/backend/question/repository/QuestionQueryRepositoryTest.java
Labels: fix

#172 refactor : 커플 끊기, 복원 관련 end-point 변경
  api/src/docs/asciidoc/api/couple/couple-delete.adoc
  api/src/docs/asciidoc/api/couple/couple-recouple.adoc
  api/src/main/java/com/lovely4k/backend/authentication/CustomSuccessHandler.java
  api/src/main/java/com/lovely4k/backend/couple/controller/CoupleController.java
  api/src/test/java/com/lovely4k/docs/couple/CoupleControllerDocsTest.java
Labels: refactor

#173 서비스 이용 정책 추가
  api/src/main/java/com/lovely4k/backend/couple/service/CoupleService.java
  api/src/test/java/com/lovely4k/backend/diary/service/DiaryServiceTest.java
  model/src/main/java/com/lovely4k/backend/member/Member.java
  model/src/main/java/com/lovely4k/backend/member/repository/MemberRepository.java
  model/src/main/java/com/lovely4k/backend/member/util/RandomUtils.java
  model/src/test/java/com/lovely4k/backend/couple/repository/CoupleQueryRepositoryTest.java
  model/src/test/java/com/lovely4k/backend/member/MemberTest.java
  model/src/test/java/com/lovely4k/backend/member/repository/MemberRepositoryTest.java
Labels: feat, refactor

#174 refactor: 다이어리 수정 api 변경 및 다이어리 이미지 업로드 관련 로직 수정
  api/src/main/java/com/lovely4k/backend/common/GlobalExceptionHandler.java
  api/src/main/java/com/lovely4k/backend/common/imageuploader/AWSS3Uploader.java
  api/src/main/java/com/lovely4k/backend/diary/controller/request/WebDiaryEditRequest.java
  api/src/main/java/com/lovely4k/backend/diary/service/DiaryImageUploader.java
  api/src/main/java/com/lovely4k/backend/diary/service/DiaryService.java
  api/src/main/java/com/lovely4k/backend/diary/service/request/DiaryEditRequest.java
  api/src/main/java/com/lovely4k/backend/diary/service/response/DiaryMarkerResponse.java
  api/src/test/java/com/lovely4k/backend/diary/service/DiaryServiceTest.java
  model/src/main/java/com/lovely4k/backend/diary/Diary.java
Labels: refactor

#175 feat : refresh토큰 발급 추가
  api/src/main/java/com/lovely4k/backend/authentication/CustomSuccessHandler.java
  api/src/main/java/com/lovely4k/backend/authentication/exception/InvalidateTokenResponseWriter.java
  api/src/main/java/com/lovely4k/backend/authentication/token/JwtFilter.java
  api/src/main/java/com/lovely4k/backend/authentication/token/SecurityConfig.java
  api/src/main/java/com/lovely4k/backend/authentication/token/TokenProvider.java
  api/src/main/java/com/lovely4k/backend/authentication/token/UserDetailsImpl.java
  api/src/main/java/com/lovely4k/backend/authentication/token/UserDetailsServiceImpl.java
  api/src/main/java/com/lovely4k/backend/calendar/service/CalendarCommandService.java
  api/src/main/java/com/lovely4k/backend/common/error/ExceptionMessage.java
  api/src/main/java/com/lovely4k/backend/common/error/GlobalExceptionHandler.java
  api/src/main/java/com/lovely4k/backend/common/error/OutsideDispatcherErrorHandler.java
  api/src/main/java/com/lovely4k/backend/common/error/ProblemDetailCreator.java
  api/src/main/java/com/lovely4k/backend/common/error/ValidationError.java
  api/src/main/java/com/lovely4k/backend/common/log/Pointcuts.java
  api/src/main/java/com/lovely4k/backend/question/service/QuestionService.java
  api/src/main/java/com/lovely4k/backend/question/service/QuestionServiceSupporter.java
  api/src/test/java/com/lovely4k/backend/ControllerTestSupport.java
  api/src/test/java/com/lovely4k/backend/member/controller/MemberControllerTest.java
  build.gradle
  model/src/main/java/com/lovely4k/backend/authentication/RefreshToken.java
  model/src/main/java/com/lovely4k/backend/authentication/RefreshTokenRepository.java
Labels: feat, refactor

#179 Release 2.9
  README.md
  api/src/docs/asciidoc/api/couple/couple-delete.adoc
  api/src/docs/asciidoc/api/couple/couple-recouple.adoc
  api/src/docs/asciidoc/api/couple/couple-temperature.adoc
  api/src/docs/asciidoc/index.adoc
  api/src/main/java/com/lovely4k/backend/authentication/CustomSuccessHandler.java
  api/src/main/java/com/lovely4k/backend/authentication/exception/InvalidateTokenResponseWriter.java
  api/src/main/java/com/lovely4k/backend/authentication/token/JwtFilter.java
  api/src/main/java/com/lovely4k/backend/authentication/token/SecurityConfig.java
  api/src/main/java/com/lovely4k/backend/authentication/token/TokenProvider.java
  api/src/main/java/com/lovely4k/backend/authentication/token/UserDetailsImpl.java
  api/src/main/java/com/lovely4k/backend/authentication/token/UserDetailsServiceImpl.java
  api/src/main/java/com/lovely4k/backend/calendar/service/CalendarCommandService.java
  api/src/main/java/com/lovely4k/backend/common/error/ExceptionMessage.java
  api/src/main/java/com/lovely4k/backend/common/error/GlobalExceptionHandler.java
  api/src/main/java/com/lovely4k/backend/common/error/OutsideDispatcherErrorHandler.java
  api/src/main/java/com/lovely4k/backend/common/error/ProblemDetailCreator.java
  api/src/main/java/com/lovely4k/backend/common/error/ValidationError.java
  api/src/main/java/com/lovely4k/backend/common/imageuploader/AWSS3Uploader.java
  api/src/main/java/com/lovely4k/backend/common/log/Pointcuts.java
  api/src/main/java/com/lovely4k/backend/common/sessionuser/LoginUserArgumentResolver.java
  api/src/main/java/com/lovely4k/backend/couple/controller/CoupleController.java
  api/src/main/java/com/lovely4k/backend/couple/service/CoupleService.java
  api/src/main/java/com/lovely4k/backend/couple/service/response/CoupleTemperatureResponse.java
  api/src/main/java/com/lovely4k/backend/diary/controller/request/WebDiaryEditRequest.java
  api/src/main/java/com/lovely4k/backend/diary/service/DiaryImageUploader.java
  api/src/main/java/com/lovely4k/backend/diary/service/DiaryService.java
  api/src/main/java/com/lovely4k/backend/diary/service/request/DiaryEditRequest.java
  api/src/main/java/com/lovely4k/backend/diary/service/response/DiaryMarkerResponse.java
  api/src/main/java/com/lovely4k/backend/question/service/QuestionService.java
  api/src/main/java/com/lovely4k/backend/question/service/QuestionServiceSupporter.java
  api/src/main/java/com/lovely4k/backend/question/service/QuestionValidator.java
  api/src/main/resources/schema/schema.sql
  api/src/test/java/com/lovely4k/backend/ControllerTestSupport.java
  api/src/test/java/com/lovely4k/backend/couple/service/CoupleServiceTest.java
  api/src/test/java/com/lovely4k/backend/diary/service/DiaryServiceTest.java
  api/src/test/java/com/lovely4k/backend/member/controller/MemberControllerTest.java
  api/src/test/java/com/lovely4k/docs/couple/CoupleControllerDocsTest.java
  build.gradle
  model/src/main/java/com/lovely4k/backend/authentication/RefreshToken.java
  model/src/main/java/com/lovely4k/backend/authentication/RefreshTokenRepository.java
  model/src/main/java/com/lovely4k/backend/diary/Diary.java
  model/src/main/java/com/lovely4k/backend/member/Member.java
  model/src/main/java/com/lovely4k/backend/member/repository/MemberRepository.java
  model/src/main/java/com/lovely4k/backend/member/util/RandomUtils.java
  model/src/main/java/com/lovely4k/backend/question/repository/QuestionQueryRepository.java
  model/src/test/java/com/lovely4k/backend/couple/repository/CoupleQueryRepositoryTest.java
  model/src/test/java/com/lovely4k/backend/member/MemberTest.java
  model/src/test/java/com/lovely4k/backend/member/repository/MemberRepositoryTest.java
  model/src/test/java/com/lovely4k/backend/question/repository/QuestionQueryRepositoryTest.java
Labels: release

#189 refactor : 다이어리 수정 로직 변경
  api/src/docs/asciidoc/api/diary/diary-edit.adoc
  api/src/main/java/com/lovely4k/backend/diary/controller/request/WebDiaryEditRequest.java
  api/src/main/java/com/lovely4k/backend/diary/service/DiaryService.java
  api/src/main/java/com/lovely4k/backend/diary/service/request/DiaryEditRequest.java
  api/src/test/java/com/lovely4k/backend/diary/controller/DiaryControllerTest.java
  api/src/test/java/com/lovely4k/backend/diary/service/DiaryServiceTest.java
  api/src/test/java/com/lovely4k/docs/diary/DiaryControllerDocsTest.java
  api/src/test/java/com/lovely4k/docs/diary/MockDiaryEditRequest.java
  model/src/main/java/com/lovely4k/backend/diary/Diary.java
  model/src/test/java/com/lovely4k/backend/diary/DiaryTest.java
Labels: refactor

#186 Refactor diary query
  api/src/main/java/com/lovely4k/backend/diary/controller/DiaryController.java
  api/src/main/java/com/lovely4k/backend/diary/service/DiaryQueryService.java
  api/src/main/java/com/lovely4k/backend/diary/service/DiaryService.java
  api/src/main/java/com/lovely4k/backend/diary/service/response/DiaryDetailResponse.java
  api/src/main/java/com/lovely4k/backend/diary/service/response/DiaryListByMarkerResponse.java
  api/src/main/java/com/lovely4k/backend/diary/service/response/PhotoListResponse.java
  api/src/main/java/com/lovely4k/backend/diary/service/response/WebDiaryDetailResponse.java
  api/src/main/java/com/lovely4k/backend/diary/service/response/WebDiaryListByMarkerResponse.java
  api/src/main/java/com/lovely4k/backend/diary/service/response/WebDiaryListResponse.java
  api/src/main/java/com/lovely4k/backend/diary/service/response/WebDiaryMarkerResponse.java
  api/src/test/java/com/lovely4k/backend/ControllerTestSupport.java
  api/src/test/java/com/lovely4k/backend/diary/service/DiaryQueryServiceTest.java
  api/src/test/java/com/lovely4k/backend/diary/service/DiaryServiceTest.java
  api/src/test/java/com/lovely4k/backend/diary/service/response/photoListResponseTest.java
  api/src/test/java/com/lovely4k/docs/diary/DiaryControllerDocsTest.java
  model/src/main/java/com/lovely4k/backend/diary/DiaryQueryRepository.java
  model/src/main/java/com/lovely4k/backend/diary/DiaryRepository.java
  model/src/main/java/com/lovely4k/backend/diary/DiaryRepositoryAdapter.java
  model/src/main/java/com/lovely4k/backend/diary/QDiaryRepository.java
  model/src/main/java/com/lovely4k/backend/diary/response/DiaryDetailResponse.java
  model/src/main/java/com/lovely4k/backend/diary/response/DiaryListResponse.java
  model/src/test/java/com/lovely4k/backend/diary/DiaryQueryRepositoryTest.java
  model/src/test/java/com/lovely4k/backend/diary/DiaryRepositoryAdapterTest.java
  model/src/test/java/com/lovely4k/backend/diary/DiaryRepositoryTest.java
  model/src/test/java/com/lovely4k/backend/diary/QDiaryRepositoryTest.java
Labels: refactor

#190 docs : token docs 추가
  api/src/docs/asciidoc/api/login/token.adoc
  api/src/docs/asciidoc/index.adoc
Labels: docs

#191 Release 3.0
  api/src/docs/asciidoc/api/diary/diary-edit.adoc
  api/src/docs/asciidoc/api/login/token.adoc
  api/src/docs/asciidoc/index.adoc
  api/src/main/java/com/lovely4k/backend/diary/controller/DiaryController.java
  api/src/main/java/com/lovely4k/backend/diary/controller/request/WebDiaryEditRequest.java
  api/src/main/java/com/lovely4k/backend/diary/service/DiaryQueryService.java
  api/src/main/java/com/lovely4k/backend/diary/service/DiaryService.java
  api/src/main/java/com/lovely4k/backend/diary/service/request/DiaryEditRequest.java
  api/src/main/java/com/lovely4k/backend/diary/service/response/DiaryDetailResponse.java
  api/src/main/java/com/lovely4k/backend/diary/service/response/DiaryListByMarkerResponse.java
  api/src/main/java/com/lovely4k/backend/diary/service/response/PhotoListResponse.java
  api/src/main/java/com/lovely4k/backend/diary/service/response/WebDiaryDetailResponse.java
  api/src/main/java/com/lovely4k/backend/diary/service/response/WebDiaryListByMarkerResponse.java
  api/src/main/java/com/lovely4k/backend/diary/service/response/WebDiaryListResponse.java
  api/src/main/java/com/lovely4k/backend/diary/service/response/WebDiaryMarkerResponse.java
  api/src/test/java/com/lovely4k/backend/ControllerTestSupport.java
  api/src/test/java/com/lovely4k/backend/diary/controller/DiaryControllerTest.java
  api/src/test/java/com/lovely4k/backend/diary/service/DiaryQueryServiceTest.java
  api/src/test/java/com/lovely4k/backend/diary/service/DiaryServiceTest.java
  api/src/test/java/com/lovely4k/backend/diary/service/response/photoListResponseTest.java
  api/src/test/java/com/lovely4k/docs/diary/DiaryControllerDocsTest.java
  api/src/test/java/com/lovely4k/docs/diary/MockDiaryEditRequest.java
  model/src/main/java/com/lovely4k/backend/diary/Diary.java
  model/src/main/java/com/lovely4k/backend/diary/DiaryQueryRepository.java
  model/src/main/java/com/lovely4k/backend/diary/DiaryRepository.java
  model/src/main/java/com/lovely4k/backend/diary/DiaryRepositoryAdapter.java
  model/src/main/java/com/lovely4k/backend/diary/QDiaryRepository.java
  model/src/main/java/com/lovely4k/backend/diary/response/DiaryDetailResponse.java
  model/src/main/java/com/lovely4k/backend/diary/response/DiaryListResponse.java
  model/src/test/java/com/lovely4k/backend/diary/DiaryQueryRepositoryTest.java
  model/src/test/java/com/lovely4k/backend/diary/DiaryRepositoryAdapterTest.java
  model/src/test/java/com/lovely4k/backend/diary/DiaryRepositoryTest.java
  model/src/test/java/com/lovely4k/backend/diary/DiaryTest.java
  model/src/test/java/com/lovely4k/backend/diary/QDiaryRepositoryTest.java
Labels: release

#193 Release 3.0
  api/src/main/java/com/lovely4k/backend/calendar/controller/CalendarController.java
  api/src/main/java/com/lovely4k/backend/calendar/service/CalendarCommandService.java
  api/src/test/java/com/lovely4k/backend/calendar/service/CalendarCommandServiceTest.java
  api/src/test/java/com/lovely4k/docs/calendar/CalendarApiDocsTest.java
  model/src/main/java/com/lovely4k/backend/calendar/Calendar.java
  model/src/main/java/com/lovely4k/backend/diary/QDiaryRepository.java
  model/src/test/java/com/lovely4k/backend/calendar/CalendarTest.java
Labels: release

#194 Release 3.0
  api/src/main/java/com/lovely4k/backend/calendar/controller/CalendarController.java
  api/src/main/java/com/lovely4k/backend/calendar/service/CalendarCommandService.java
  api/src/test/java/com/lovely4k/backend/calendar/service/CalendarCommandServiceTest.java
  api/src/test/java/com/lovely4k/docs/calendar/CalendarApiDocsTest.java
  model/src/main/java/com/lovely4k/backend/calendar/Calendar.java
  model/src/main/java/com/lovely4k/backend/diary/QDiaryRepository.java
  model/src/test/java/com/lovely4k/backend/calendar/CalendarTest.java
Labels: release
