Repository Lovely-4K/love-backend, pull requests merged in 2023-10, with the labels that each got.

#4 feat : member 엔티티 추가
  model/src/main/java/com/lovely4k/backend/member/Member.java
Labels: feat

#6 feat : couple 엔티티 추가 [#5]
  model/src/main/java/com/lovely4k/backend/couple/Couple.java
Labels: feat

#9 feat : 다이어리 관련 entity 생성 [#7, #8]
  model/src/main/java/com/lovely4k/backend/diary/Diary.java
  model/src/main/java/com/lovely4k/backend/diary/Photos.java
  model/src/main/java/com/lovely4k/backend/location/Category.java
  model/src/main/java/com/lovely4k/backend/location/Location.java
Labels: feat

#12 feat : question 관련 entity 생성 [#10, #11]
  model/src/main/java/com/lovely4k/backend/question/Question.java
  model/src/main/java/com/lovely4k/backend/question/QuestionChoices.java
  model/src/main/java/com/lovely4k/backend/question/QuestionForm.java
Labels: feat

#14 feat : BaseTimeEntity 추가 [#13]
  model/src/main/java/com/lovely4k/backend/ModelApplication.java
  model/src/main/java/com/lovely4k/backend/common/jpa/BaseTimeEntity.java
  model/src/main/java/com/lovely4k/backend/common/jpa/JpaConfig.java
  model/src/main/java/com/lovely4k/backend/couple/Couple.java
  model/src/main/java/com/lovely4k/backend/diary/Diary.java
  model/src/main/java/com/lovely4k/backend/location/Location.java
  model/src/main/java/com/lovely4k/backend/member/Member.java
  model/src/main/java/com/lovely4k/backend/question/Question.java
  model/src/main/java/com/lovely4k/backend/question/QuestionForm.java
Labels: feat

#16 chore : Profile별 yml파일 설정 [#15]
  api/src/main/resources/application-local.yaml
  api/src/main/resources/application.yaml
  api/src/main/resources/schema/schema.sql
  model/build.gradle
Labels: chore

#18 feat : API 공통 응답 작성 [#17]
  api/src/main/java/com/lovely4k/backend/common/ApiResponse.java
  api/src/main/java/com/lovely4k/backend/common/GlobalExceptionHandler.java
  api/src/main/java/com/lovely4k/backend/common/ProblemDetailCreator.java
  api/src/main/java/com/lovely4k/backend/common/ValidationError.java
Labels: feat

#19 feat : 테스트 Support Class 작성
  api/src/test/java/com/lovely4k/backend/ControllerTestSupport.java
  api/src/test/java/com/lovely4k/docs/RestDocsSupport.java
Labels: feat

#23 docs : diary 문서화 작업 진행 [#22]
  api/src/main/java/com/lovely4k/backend/common/ApiResponse.java
  api/src/main/java/com/lovely4k/backend/diary/controller/DiaryController.java
  api/src/main/java/com/lovely4k/backend/diary/controller/request/DiaryEditRequest.java
  api/src/main/java/com/lovely4k/backend/diary/service/response/DiaryDetailResponse.java
  api/src/main/java/com/lovely4k/backend/diary/service/response/DiaryListResponse.java
  api/src/test/java/com/lovely4k/docs/diary/DiaryControllerDocsTest.java
  api/src/test/java/com/lovely4k/docs/diary/MockDiaryEditRequest.java
Labels: docs

#25 docs : 커플, 프로필 API 명세서 작성 [#24]
  api/src/main/java/com/lovely4k/backend/common/ApiResponse.java
  api/src/main/java/com/lovely4k/backend/couple/controller/CoupleController.java
  api/src/main/java/com/lovely4k/backend/couple/controller/request/CoupleProfileEditRequest.java
  api/src/main/java/com/lovely4k/backend/couple/service/response/CoupleProfileGetResponse.java
  api/src/main/java/com/lovely4k/backend/member/controller/MemberController.java
  api/src/main/java/com/lovely4k/backend/member/controller/request/MemberProfileEditRequest.java
  api/src/main/java/com/lovely4k/backend/member/service/response/MemberProfileGetResponse.java
  api/src/test/java/com/lovely4k/backend/ControllerTestSupport.java
  api/src/test/java/com/lovely4k/docs/CoupleControllerDocsTest.java
  api/src/test/java/com/lovely4k/docs/MemberControllerDocsTest.java
Labels: docs

#26 docs : question api restdocs 작성
  api/src/main/java/com/lovely4k/backend/common/ApiResponse.java
  api/src/main/java/com/lovely4k/backend/question/controller/QuestionController.java
  api/src/main/java/com/lovely4k/backend/question/controller/request/CreateQuestionFormRequest.java
  api/src/main/java/com/lovely4k/backend/question/service/QuestionService.java
  api/src/main/java/com/lovely4k/backend/question/service/response/CreateQuestionFormResponse.java
  api/src/main/java/com/lovely4k/backend/question/service/response/CreateQuestionResponse.java
  api/src/main/java/com/lovely4k/backend/question/service/response/DailyQuestionResponse.java
  api/src/main/java/com/lovely4k/backend/question/service/response/QuestionDetailsResponse.java
  api/src/test/java/com/lovely4k/backend/ControllerTestSupport.java
  api/src/test/java/com/lovely4k/docs/question/QuestionApiDocs.java
Labels: docs

#33 feat : 다이어리 생성 관련 service, repository 구현 [#20]
  api/src/main/java/com/lovely4k/backend/diary/controller/DiaryController.java
  api/src/main/java/com/lovely4k/backend/diary/controller/request/WebDiaryCreateRequest.java
  api/src/main/java/com/lovely4k/backend/diary/service/DiaryService.java
  api/src/main/java/com/lovely4k/backend/diary/service/request/DiaryCreateRequest.java
  api/src/test/java/com/lovely4k/backend/IntegrationTestSupport.java
  api/src/test/java/com/lovely4k/backend/diary/controller/DiaryControllerTest.java
  api/src/test/java/com/lovely4k/backend/diary/controller/MockDiaryCreateRequest.java
  api/src/test/java/com/lovely4k/backend/diary/service/DiaryServiceTest.java
  api/src/test/java/com/lovely4k/backend/diary/service/request/DiaryCreateRequestTest.java
  api/src/test/java/com/lovely4k/docs/diary/DiaryControllerDocsTest.java
  api/src/test/java/com/lovely4k/docs/diary/MockDiaryCreateRequest.java
  model/src/main/java/com/lovely4k/backend/diary/Diary.java
  model/src/main/java/com/lovely4k/backend/diary/DiaryRepository.java
  model/src/main/java/com/lovely4k/backend/location/Location.java
  model/src/main/java/com/lovely4k/backend/location/LocationRepository.java
  model/src/main/java/com/lovely4k/backend/member/Member.java
  model/src/main/java/com/lovely4k/backend/member/MemberRepository.java
  model/src/test/java/com/lovely4k/backend/diary/DiaryTest.java
  model/src/test/java/com/lovely4k/backend/location/LocationTest.java
Labels: feat

#49 feat : 다이어리 삭제 기능 구현 [#46, #47]
  api/src/main/java/com/lovely4k/backend/diary/controller/DiaryController.java
  api/src/main/java/com/lovely4k/backend/diary/service/DiaryService.java
  api/src/test/java/com/lovely4k/backend/diary/service/DiaryServiceTest.java
  api/src/test/java/com/lovely4k/docs/diary/DiaryControllerDocsTest.java
  model/src/main/java/com/lovely4k/backend/diary/Diary.java
  model/src/test/java/com/lovely4k/backend/diary/DiaryTest.java
Labels: feat

#52 feat : 초대 코드 생성 기능 구현 [#50]
  api/src/main/java/com/lovely4k/backend/couple/controller/CoupleController.java
  api/src/main/java/com/lovely4k/backend/couple/service/CoupleService.java
  api/src/main/java/com/lovely4k/backend/couple/service/response/InvitationCodeCreateResponse.java
  api/src/main/resources/schema/schema.sql
  api/src/test/java/com/lovely4k/backend/ControllerTestSupport.java
  api/src/test/java/com/lovely4k/backend/couple/controller/CoupleControllerTest.java
  api/src/test/java/com/lovely4k/backend/couple/service/CoupleServiceTest.java
  api/src/test/java/com/lovely4k/docs/couple/CoupleControllerDocsTest.java
  model/src/main/java/com/lovely4k/backend/couple/Couple.java
Labels: feat

#57 feat : 다이어리 목록 조회 기능 구현 [#46, #56]
  api/src/main/java/com/lovely4k/backend/diary/controller/DiaryController.java
  api/src/main/java/com/lovely4k/backend/diary/service/DiaryService.java
  api/src/main/java/com/lovely4k/backend/diary/service/response/DiaryListResponse.java
  api/src/test/java/com/lovely4k/docs/RestDocsSupport.java
  api/src/test/java/com/lovely4k/docs/diary/DiaryControllerDocsTest.java
  model/build.gradle
  model/src/main/java/com/lovely4k/backend/diary/DiaryRepositoryAdapter.java
  model/src/main/java/com/lovely4k/backend/diary/QDiaryRepository.java
  model/src/main/java/com/lovely4k/backend/location/Category.java
  model/src/test/java/com/lovely4k/backend/IntegrationTestSupport.java
  model/src/test/java/com/lovely4k/backend/diary/QDiaryRepositoryTest.java
  model/src/test/java/com/lovely4k/backend/location/CategoryTest.java
Labels: feat

#58 feat : 초대코드를 통한 커플 등록 [#53]
  api/src/main/java/com/lovely4k/backend/couple/controller/CoupleController.java
  api/src/main/java/com/lovely4k/backend/couple/service/CoupleService.java
  api/src/test/java/com/lovely4k/backend/couple/controller/CoupleControllerTest.java
  api/src/test/java/com/lovely4k/backend/couple/service/CoupleServiceTest.java
  api/src/test/java/com/lovely4k/docs/couple/CoupleControllerDocsTest.java
  model/src/main/java/com/lovely4k/backend/couple/Couple.java
  model/src/main/java/com/lovely4k/backend/couple/repository/CoupleRepository.java
Labels: feat

#59 feat : 커플 프로필 조회 [#54]
  api/src/main/java/com/lovely4k/backend/couple/controller/CoupleController.java
  api/src/main/java/com/lovely4k/backend/couple/service/CoupleService.java
  api/src/main/java/com/lovely4k/backend/couple/service/response/CoupleProfileGetResponse.java
  api/src/test/java/com/lovely4k/backend/couple/controller/CoupleControllerTest.java
  api/src/test/java/com/lovely4k/backend/couple/service/CoupleServiceTest.java
  api/src/test/java/com/lovely4k/docs/couple/CoupleControllerDocsTest.java
Labels: feat

#60 feat : 커플 프로필 수정 [#55]
  api/src/main/java/com/lovely4k/backend/couple/controller/CoupleController.java
  api/src/main/java/com/lovely4k/backend/couple/controller/request/CoupleProfileEditRequest.java
  api/src/main/java/com/lovely4k/backend/couple/service/CoupleService.java
  api/src/main/java/com/lovely4k/backend/couple/service/request/CoupleProfileEditServiceRequest.java
  api/src/test/java/com/lovely4k/backend/couple/controller/CoupleControllerTest.java
  api/src/test/java/com/lovely4k/backend/couple/controller/request/TestCoupleProfileEditRequest.java
  api/src/test/java/com/lovely4k/backend/couple/service/CoupleServiceTest.java
  api/src/test/java/com/lovely4k/docs/couple/CoupleControllerDocsTest.java
  model/src/main/java/com/lovely4k/backend/couple/Couple.java
  model/src/main/java/com/lovely4k/backend/member/Member.java
Labels: feat

#61 docs : 초대코드 생성 API restdocs 작성
  api/src/test/java/com/lovely4k/docs/couple/CoupleControllerDocsTest.java
Labels: feat

#62 test : question 도메인 테스트 추가
  api/src/test/java/com/lovely4k/backend/ApiApplicationTests.java
  build.gradle
  model/src/test/java/com/lovely4k/backend/ModelApplicationTests.java
  model/src/test/java/com/lovely4k/backend/question/QuestionChoicesTest.java
  model/src/test/java/com/lovely4k/backend/question/QuestionTest.java
Labels: test

#63 test : diary 추가 테스트 작성
  api/src/main/java/com/lovely4k/backend/diary/controller/DiaryController.java
  api/src/main/java/com/lovely4k/backend/diary/service/DiaryService.java
  api/src/main/java/com/lovely4k/backend/diary/service/response/DiaryDetailResponse.java
  api/src/main/java/com/lovely4k/backend/diary/service/response/DiaryListResponse.java
  api/src/main/java/com/lovely4k/backend/diary/service/response/PhotoListResponse.java
  api/src/test/java/com/lovely4k/backend/diary/service/DiaryServiceTest.java
  api/src/test/java/com/lovely4k/backend/diary/service/response/photoListResponseTest.java
  api/src/test/java/com/lovely4k/docs/diary/DiaryControllerDocsTest.java
  model/src/main/java/com/lovely4k/backend/diary/DiaryRepositoryAdapter.java
  model/src/main/java/com/lovely4k/backend/location/Category.java
  model/src/test/java/com/lovely4k/backend/diary/DiaryRepositoryAdapterTest.java
  model/src/test/java/com/lovely4k/backend/diary/DiaryTest.java
  model/src/test/java/com/lovely4k/backend/diary/PhotosTest.java
  model/src/test/java/com/lovely4k/backend/location/CategoryTest.java
Labels: test

#65 refactor : diary 관련 request Parameter memberId -> coupleId 변경
  api/src/main/java/com/lovely4k/backend/diary/controller/DiaryController.java
  api/src/main/java/com/lovely4k/backend/diary/service/DiaryService.java
  api/src/test/java/com/lovely4k/backend/diary/service/DiaryServiceTest.java
  api/src/test/java/com/lovely4k/docs/diary/DiaryControllerDocsTest.java
Labels: refactor

#66 refactor : 코드 리뷰 반영
  api/src/main/java/com/lovely4k/backend/couple/controller/CoupleController.java
  api/src/main/java/com/lovely4k/backend/couple/service/CoupleService.java
  api/src/main/java/com/lovely4k/backend/couple/service/response/CoupleProfileGetResponse.java
  api/src/main/java/com/lovely4k/backend/member/controller/request/MemberProfileEditRequest.java
  api/src/main/java/com/lovely4k/backend/member/service/MemberService.java
  api/src/main/java/com/lovely4k/backend/member/service/request/MemberProfileEditServiceRequest.java
  api/src/main/java/com/lovely4k/backend/member/service/response/MemberProfileGetResponse.java
  api/src/main/resources/schema/schema.sql
  api/src/test/java/com/lovely4k/backend/couple/controller/CoupleControllerTest.java
  api/src/test/java/com/lovely4k/backend/couple/service/CoupleServiceTest.java
  api/src/test/java/com/lovely4k/backend/diary/service/DiaryServiceTest.java
  api/src/test/java/com/lovely4k/backend/diary/service/request/DiaryCreateRequestTest.java
  api/src/test/java/com/lovely4k/backend/member/controller/MemberControllerTest.java
  api/src/test/java/com/lovely4k/backend/member/service/MemberServiceTest.java
  api/src/test/java/com/lovely4k/docs/couple/CoupleControllerDocsTest.java
  api/src/test/java/com/lovely4k/docs/member/MemberControllerDocsTest.java
  model/src/main/java/com/lovely4k/backend/couple/Couple.java
  model/src/main/java/com/lovely4k/backend/diary/Diary.java
  model/src/main/java/com/lovely4k/backend/member/Member.java
  model/src/test/java/com/lovely4k/backend/couple/CoupleTest.java
  model/src/test/java/com/lovely4k/backend/diary/DiaryTest.java
  model/src/test/java/com/lovely4k/backend/member/MemberTest.java
Labels: refactor

#64 refactor : pr 리뷰 반영(1차 스프린트)
  api/src/main/java/com/lovely4k/backend/couple/controller/CoupleController.java
  api/src/main/java/com/lovely4k/backend/couple/service/CoupleService.java
  api/src/main/java/com/lovely4k/backend/couple/service/response/CoupleProfileGetResponse.java
  api/src/main/java/com/lovely4k/backend/member/controller/request/MemberProfileEditRequest.java
  api/src/main/java/com/lovely4k/backend/member/service/request/MemberProfileEditServiceRequest.java
  api/src/main/java/com/lovely4k/backend/member/service/response/MemberProfileGetResponse.java
  api/src/main/resources/schema/schema.sql
  api/src/test/java/com/lovely4k/backend/couple/controller/CoupleControllerTest.java
  api/src/test/java/com/lovely4k/backend/couple/service/CoupleServiceTest.java
  api/src/test/java/com/lovely4k/backend/diary/service/DiaryServiceTest.java
  api/src/test/java/com/lovely4k/backend/diary/service/request/DiaryCreateRequestTest.java
  api/src/test/java/com/lovely4k/backend/member/controller/MemberControllerTest.java
  api/src/test/java/com/lovely4k/backend/member/service/MemberServiceTest.java
  api/src/test/java/com/lovely4k/docs/couple/CoupleControllerDocsTest.java
  api/src/test/java/com/lovely4k/docs/member/MemberControllerDocsTest.java
  model/src/main/java/com/lovely4k/backend/couple/Couple.java
  model/src/main/java/com/lovely4k/backend/diary/Diary.java
  model/src/main/java/com/lovely4k/backend/member/Member.java
  model/src/test/java/com/lovely4k/backend/diary/DiaryTest.java
Labels: refactor

#67 Docs restdocs
  api/src/docs/asciidoc/api/common/http-status-code.adoc
  api/src/docs/asciidoc/api/common/http-verbs.adoc
  api/src/docs/asciidoc/api/couple/couple-invitationCode-get.adoc
  api/src/docs/asciidoc/api/couple/couple-profile-edit.adoc
  api/src/docs/asciidoc/api/couple/couple-profile-get.adoc
  api/src/docs/asciidoc/api/couple/couple-register.adoc
  api/src/docs/asciidoc/api/diary/diary-create.adoc
  api/src/docs/asciidoc/api/diary/diary-delete.adoc
  api/src/docs/asciidoc/api/diary/diary-edit.adoc
  api/src/docs/asciidoc/api/diary/diary-getDetail.adoc
  api/src/docs/asciidoc/api/diary/diary-getList.adoc
  api/src/docs/asciidoc/api/member/member-profile-edit.adoc
  api/src/docs/asciidoc/api/member/member-profile-get.adoc
  api/src/docs/asciidoc/api/question/questions.adoc
  api/src/docs/asciidoc/index.adoc
  api/src/main/java/com/lovely4k/backend/couple/controller/CoupleController.java
  api/src/main/java/com/lovely4k/backend/couple/service/CoupleService.java
  api/src/main/java/com/lovely4k/backend/diary/controller/DiaryController.java
  api/src/test/java/com/lovely4k/backend/couple/controller/CoupleControllerTest.java
  api/src/test/java/com/lovely4k/backend/couple/service/CoupleServiceTest.java
  api/src/test/java/com/lovely4k/docs/couple/CoupleControllerDocsTest.java
  api/src/test/java/com/lovely4k/docs/diary/DiaryControllerDocsTest.java
  api/src/test/java/com/lovely4k/docs/question/QuestionApiDocsTest.java
Labels: docs

#71 release : V1 배포 (일부 설정 변경)
  api/src/main/java/com/lovely4k/backend/common/config/WebConfig.java
  api/src/main/resources/application-local.yaml
  api/src/main/resources/application.yaml
  api/src/main/resources/schema/schema.sql
  api/src/main/resources/static/docs/index.html
  api/src/test/java/com/lovely4k/backend/question/service/QuestionServiceConcurrencyTest.java
Labels: refactor
